'use client'

import { useEffect, useState, useCallback, useMemo } from 'react'
import { createClient } from '@/lib/supabase/client'
import { ModuleWorkspaceShell } from '@/components/modules/ModuleWorkspaceShell'
import { EmptyModuleState } from '@/components/modules/shared/EmptyModuleState'
import { StatusBadge } from '@/components/modules/shared/StatusBadge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Plus, Pencil, Trash2, Loader2, Search, ShieldCheck } from 'lucide-react'

interface ModuleWorkspaceProps { module: { slug: string; name: string; cat: string; desc: string; longDesc: string }; sectorSlug: string; settingsHref: string }
type ProvisionStatus = 'aktiv' | 'utnyttjad' | 'frislappt'
interface Item { id: string; order_ref: string; customer: string; description: string; provision_amount: number; actual_cost: number; date: string; expiry_date: string; status: ProvisionStatus }
const STATUS_LABELS: Record<ProvisionStatus, string> = { aktiv: 'Aktiv', utnyttjad: 'Utnyttjad', frislappt: 'Frisläppt' }
const STATUS_VARIANT: Record<ProvisionStatus, 'warning' | 'success' | 'neutral'> = { aktiv: 'warning', utnyttjad: 'success', frislappt: 'neutral' }
function generateId(): string { return Date.now().toString(36) + Math.random().toString(36).substring(2, 7) }
function fmt(n: number): string { return new Intl.NumberFormat('sv-SE', { maximumFractionDigits: 0 }).format(n) }
const DEFAULT_ITEMS: Item[] = [
  { id: '1', order_ref: 'AO-2025-001', customer: 'Anders J', description: 'Garantiavsättning bromsbyte', provision_amount: 2000, actual_cost: 0, date: '2025-03-15', expiry_date: '2026-03-15', status: 'aktiv' },
  { id: '2', order_ref: 'AO-2024-045', customer: 'Maria K', description: 'Garantiarbete motor', provision_amount: 5000, actual_cost: 3200, date: '2024-11-01', expiry_date: '2025-11-01', status: 'utnyttjad' },
]
const EMPTY_FORM = { order_ref: '', customer: '', description: '', provision_amount: '', actual_cost: '0', date: '', expiry_date: '', status: 'aktiv' as ProvisionStatus }

export function GarantiavsattningWorkspace({ module: mod, sectorSlug, settingsHref }: ModuleWorkspaceProps) {
  const supabase = createClient()
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [items, setItems] = useState<Item[]>([]); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [form, setForm] = useState(EMPTY_FORM); const [deleteDialogOpen, setDeleteDialogOpen] = useState(false); const [toDelete, setToDelete] = useState<Item | null>(null); const [searchQuery, setSearchQuery] = useState('')
  const save = useCallback(async (d: Item[]) => { setSaving(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setSaving(false); return }; await supabase.from('module_configs').upsert({ user_id: user.id, sector_slug: sectorSlug, module_slug: mod.slug, config_key: 'warranty_items', config_value: d }, { onConflict: 'user_id,sector_slug,module_slug,config_key' }); setSaving(false) }, [supabase, sectorSlug, mod.slug])
  const fetch_ = useCallback(async () => { setLoading(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setLoading(false); return }; const { data } = await supabase.from('module_configs').select('config_value').eq('user_id', user.id).eq('sector_slug', sectorSlug).eq('module_slug', mod.slug).eq('config_key', 'warranty_items').maybeSingle(); if (data?.config_value && Array.isArray(data.config_value) && data.config_value.length > 0) { setItems(data.config_value as Item[]) } else { setItems(DEFAULT_ITEMS); await supabase.from('module_configs').upsert({ user_id: user.id, sector_slug: sectorSlug, module_slug: mod.slug, config_key: 'warranty_items', config_value: DEFAULT_ITEMS }, { onConflict: 'user_id,sector_slug,module_slug,config_key' }) }; setLoading(false) }, [supabase, sectorSlug, mod.slug])
  useEffect(() => { fetch_() }, [fetch_])
  const filtered = useMemo(() => { let r = items; if (searchQuery.trim()) { const q = searchQuery.toLowerCase(); r = r.filter((i) => i.order_ref.toLowerCase().includes(q) || i.customer.toLowerCase().includes(q)) }; return r.sort((a, b) => b.date.localeCompare(a.date)) }, [items, searchQuery])
  const stats = useMemo(() => ({ totalProvision: items.filter(i => i.status === 'aktiv').reduce((s, i) => s + i.provision_amount, 0), totalActual: items.reduce((s, i) => s + i.actual_cost, 0), activeCount: items.filter(i => i.status === 'aktiv').length, totalCount: items.length }), [items])
  function openNew() { setEditing(null); setForm({ ...EMPTY_FORM }); setDialogOpen(true) }
  function openEdit(i: Item) { setEditing(i); setForm({ order_ref: i.order_ref, customer: i.customer, description: i.description, provision_amount: String(i.provision_amount), actual_cost: String(i.actual_cost), date: i.date, expiry_date: i.expiry_date, status: i.status }); setDialogOpen(true) }
  async function handleSave() { const entry: Item = { id: editing?.id ?? generateId(), order_ref: form.order_ref.trim(), customer: form.customer.trim(), description: form.description.trim(), provision_amount: parseFloat(form.provision_amount) || 0, actual_cost: parseFloat(form.actual_cost) || 0, date: form.date, expiry_date: form.expiry_date, status: form.status }; const u = editing ? items.map((i) => i.id === editing.id ? entry : i) : [...items, entry]; setItems(u); setDialogOpen(false); await save(u) }
  function openDel(i: Item) { setToDelete(i); setDeleteDialogOpen(true) }
  async function handleDel() { if (!toDelete) return; const u = items.filter((i) => i.id !== toDelete.id); setItems(u); setDeleteDialogOpen(false); setToDelete(null); await save(u) }

  return (
    <>
      <ModuleWorkspaceShell title={mod.name} description={mod.desc} category="bokforing" sectorName="Fordon & Verkstad" backHref={`/m/${sectorSlug}`} settingsHref={settingsHref} actions={<Button onClick={openNew}><Plus className="mr-2 h-4 w-4" />Ny avsättning</Button>}>
        {loading ? <div className="flex items-center justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div> : (
          <div className="space-y-6">
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <Card><CardHeader className="pb-2"><CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Aktiv avsättning (2290)</CardTitle></CardHeader><CardContent><span className="text-2xl font-semibold tracking-tight">{fmt(stats.totalProvision)}</span><span className="text-sm text-muted-foreground ml-1">kr</span></CardContent></Card>
              <Card><CardHeader className="pb-2"><CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Faktisk kostnad</CardTitle></CardHeader><CardContent><span className="text-2xl font-semibold tracking-tight">{fmt(stats.totalActual)}</span><span className="text-sm text-muted-foreground ml-1">kr</span></CardContent></Card>
              <Card><CardHeader className="pb-2"><CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Aktiva garantier</CardTitle></CardHeader><CardContent><span className="text-2xl font-semibold tracking-tight">{stats.activeCount}</span></CardContent></Card>
              <Card><CardHeader className="pb-2"><CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Totalt</CardTitle></CardHeader><CardContent><span className="text-2xl font-semibold tracking-tight">{stats.totalCount}</span></CardContent></Card>
            </div>
            <div className="flex items-center gap-3"><div className="relative flex-1 max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input placeholder="Sök order eller kund..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="pl-9" /></div>{saving && <div className="flex items-center gap-2 text-xs text-muted-foreground"><Loader2 className="h-3.5 w-3.5 animate-spin" />Sparar...</div>}</div>
            {filtered.length === 0 ? <EmptyModuleState icon={ShieldCheck} title="Inga garantiavsättningar" description="Skapa garantiavsättningar för att reservera medel på konto 2290." actionLabel="Ny avsättning" onAction={openNew} /> : (
              <div className="rounded-xl border border-border overflow-hidden"><Table><TableHeader><TableRow className="bg-muted/50"><TableHead className="font-medium">Order</TableHead><TableHead className="font-medium">Kund</TableHead><TableHead className="font-medium">Beskrivning</TableHead><TableHead className="font-medium text-right">Avsättning</TableHead><TableHead className="font-medium text-right">Faktisk</TableHead><TableHead className="font-medium">Utgår</TableHead><TableHead className="font-medium">Status</TableHead><TableHead className="font-medium text-right">Åtgärder</TableHead></TableRow></TableHeader><TableBody>{filtered.map((i) => (<TableRow key={i.id}><TableCell className="font-mono">{i.order_ref}</TableCell><TableCell>{i.customer}</TableCell><TableCell>{i.description}</TableCell><TableCell className="text-right tabular-nums">{fmt(i.provision_amount)}</TableCell><TableCell className="text-right tabular-nums">{fmt(i.actual_cost)}</TableCell><TableCell>{i.expiry_date}</TableCell><TableCell><StatusBadge label={STATUS_LABELS[i.status]} variant={STATUS_VARIANT[i.status]} /></TableCell><TableCell className="text-right"><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" onClick={() => openEdit(i)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-red-600 hover:text-red-700" onClick={() => openDel(i)}><Trash2 className="h-4 w-4" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div>
            )}
          </div>
        )}
      </ModuleWorkspaceShell>
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{editing ? 'Redigera' : 'Ny garantiavsättning'}</DialogTitle><DialogDescription>Avsättningen bokförs på konto 2290 och frisläpps vid faktisk garantikostnad.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><div className="grid grid-cols-2 gap-4"><div className="grid gap-2"><Label>Orderreferens *</Label><Input value={form.order_ref} onChange={(e) => setForm((f) => ({ ...f, order_ref: e.target.value }))} /></div><div className="grid gap-2"><Label>Kund *</Label><Input value={form.customer} onChange={(e) => setForm((f) => ({ ...f, customer: e.target.value }))} /></div></div><div className="grid gap-2"><Label>Beskrivning</Label><Input value={form.description} onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))} /></div><div className="grid grid-cols-3 gap-4"><div className="grid gap-2"><Label>Avsättning (kr) *</Label><Input type="number" min={0} value={form.provision_amount} onChange={(e) => setForm((f) => ({ ...f, provision_amount: e.target.value }))} /></div><div className="grid gap-2"><Label>Faktisk kostnad</Label><Input type="number" min={0} value={form.actual_cost} onChange={(e) => setForm((f) => ({ ...f, actual_cost: e.target.value }))} /></div><div className="grid gap-2"><Label>Status</Label><Select value={form.status} onValueChange={(v) => setForm((f) => ({ ...f, status: v as ProvisionStatus }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="aktiv">Aktiv</SelectItem><SelectItem value="utnyttjad">Utnyttjad</SelectItem><SelectItem value="frislappt">Frisläppt</SelectItem></SelectContent></Select></div></div><div className="grid grid-cols-2 gap-4"><div className="grid gap-2"><Label>Datum *</Label><Input type="date" value={form.date} onChange={(e) => setForm((f) => ({ ...f, date: e.target.value }))} /></div><div className="grid gap-2"><Label>Utgår</Label><Input type="date" value={form.expiry_date} onChange={(e) => setForm((f) => ({ ...f, expiry_date: e.target.value }))} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>Avbryt</Button><Button onClick={handleSave} disabled={!form.order_ref.trim() || !form.customer.trim()}>{editing ? 'Uppdatera' : 'Skapa'}</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Ta bort</DialogTitle><DialogDescription>Ta bort garantiavsättning för <span className="font-semibold">{toDelete?.order_ref}</span>?</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteDialogOpen(false)}>Avbryt</Button><Button variant="destructive" onClick={handleDel}><Trash2 className="mr-2 h-4 w-4" />Ta bort</Button></DialogFooter></DialogContent></Dialog>
    </>
  )
}
