import {
  UtensilsCrossed,
  BedDouble,
  Monitor,
  HardHat,
  HeartPulse,
  Store,
  ShoppingCart,
  Scissors,
  Truck,
  Scale,
  GraduationCap,
  Wheat,
  Film,
  Dumbbell,
  Wrench,
  UserPlus,
  Factory,
  Briefcase,
  PartyPopper,
  Building,
  type LucideIcon,
} from 'lucide-react'

export type ModuleCategory = 'bokforing' | 'rapport' | 'import' | 'operativ'

export interface ModuleItem {
  slug: string
  name: string
  cat: ModuleCategory
  desc: string
  longDesc: string
}

export interface Sector {
  slug: string
  name: string
  icon: LucideIcon
  description: string
  modules: ModuleItem[]
}

export const CATEGORY_LABELS: Record<ModuleCategory, string> = {
  bokforing: 'Bokföring & Skatt',
  rapport: 'Branschrapporter',
  import: 'Smart import',
  operativ: 'Operativa moduler',
}

export const sectors: Sector[] = [
  {
    slug: 'restaurang', name: 'Restaurang & Café', icon: UtensilsCrossed,
    description: 'Menyhantering, bordsbokning & kassa',
    modules: [
      { slug: 'restaurangkontoplan', name: 'Restaurangkontoplan', cat: 'bokforing', desc: 'BAS-kontoplan förberedd för restaurang med uppdelning per intäktstyp', longDesc: 'BAS-kontoplan förberedd för restaurang med uppdelning per intäktstyp. Nyckelfunktioner: Separata konton för mat (3001), dryck (3002), alkohol (3003), take-away; auto-kontosättning från kassaimport' },
      { slug: 'momssplit-mat-dryck', name: 'Momssplit mat/dryck', cat: 'bokforing', desc: 'Automatisk uppdelning av moms 12% (mat) vs 25% (alkohol, dryck)', longDesc: 'Automatisk uppdelning av moms 12% (mat) vs 25% (alkohol, dryck). Nyckelfunktioner: Regelmotor för momsfördelning, hantering av blandade kvitton, månadsavstämning per momssats' },
      { slug: 'dagskassaavstamning', name: 'Dagskassaavstämning', cat: 'bokforing', desc: 'Stäm av kassans Z-rapport mot faktisk kassa och bank', longDesc: 'Stäm av kassans Z-rapport mot faktisk kassa och bank. Nyckelfunktioner: Z-rapport-import, avvikelseanalys (svinn, differens), verifikation per dag' },
      { slug: 'tipsbokforing', name: 'Tipsbokföring', cat: 'bokforing', desc: 'Bokför dricks — arbetsgivaravgift på kartdricks, skattefri kontantdricks', longDesc: 'Bokför dricks korrekt — arbetsgivaravgift på kartdricks, skattefri kontantdricks. Nyckelfunktioner: Fördelning per anställd, arbetsgivaravgiftsberäkning, konto 7699/7010-koppling' },
      { slug: 'personalliggare', name: 'Personalliggare', cat: 'bokforing', desc: 'Elektronisk personalliggare enligt krav från Skatteverket', longDesc: 'Elektronisk personalliggare enligt krav från Skatteverket. Nyckelfunktioner: Daglig registrering in/ut, exportformat för kontroll, koppla till lönekostnad' },
      { slug: 'alkoholpunktskatt', name: 'Alkohol & Accis', cat: 'bokforing', desc: 'Punktskattehantering för alkoholservering', longDesc: 'Hantera punktskatt vid egenbrygd/import av alkohol. Nyckelfunktioner: Accisberäkning, lagerrapportering, Tullverket-format' },
      { slug: 'representationsbokforing', name: 'Representationsbokföring', cat: 'bokforing', desc: 'Bokför representation med rätt avdragsgränser', longDesc: 'Bokför representation med rätt avdragsgränser. Nyckelfunktioner: Automatisk split avdragsgill/ej avdragsgill del, 90 SEK-gräns internt, momsavdrag' },
      { slug: 'matkostnad', name: 'Matkostnad (Food Cost %)', cat: 'rapport', desc: 'Livsmedelskostnad som andel av matintäkt', longDesc: 'Livsmedelskostnad som andel av matintäkt. Nyckelfunktioner: Daglig/veckovis/månadsvis %, mål vs utfall, trendkurva, larmgräns' },
      { slug: 'personalkostnad-vs-omsattning', name: 'Personalkostnad vs omsättning', cat: 'rapport', desc: 'Personalkostnad som andel av total omsättning', longDesc: 'Spåra personalkostnad som andel av total omsättning. Nyckelfunktioner: Målvärde (typiskt 30-35%), trend, jämförelse budget' },
      { slug: 'svinnrapport', name: 'Svinnrapport', cat: 'rapport', desc: 'Analysera matsvinn i kronor och procent', longDesc: 'Analysera matsvinn i kronor och procent. Nyckelfunktioner: Svinn per kategori, kostnad, svinn-till-omsättning' },
      { slug: 'revpash', name: 'RevPASH', cat: 'rapport', desc: 'Revenue per Available Seat Hour', longDesc: 'Revenue per available seat hour. Nyckelfunktioner: Intäkt per stolstimme, jämförelse per pass (lunch/middag), kapacitetsoptimering' },
      { slug: 'z-rapport-import', name: 'Z-rapport-import', cat: 'import', desc: 'Importera dagskassarapport från kassasystem', longDesc: 'Importera dagskassarapport från kassasystem. Nyckelfunktioner: CSV/Excel från iZettle, Trivec, Square, Orderbird; auto-bokför med momssplit och kontosättning' },
      { slug: 'leverantorsfaktura-import', name: 'Leverantörsfaktura-import', cat: 'import', desc: 'Importera leverantörsfakturor för matinköp', longDesc: 'Importera leverantörsfakturor för matinköp. Nyckelfunktioner: Parsning av leverantörsformat (Martin & Servera, Menigo), kostnadsfördelning per kategori' },
      { slug: 'menyhantering', name: 'Menyhantering', cat: 'operativ', desc: 'Bygg och publicera menyer digitalt', longDesc: 'Bygg och publicera menyer digitalt. Nyckelfunktioner: Menybyggare, säsongsbyte, allergenmarkering, prissättning per kanal' },
      { slug: 'bordsbokning', name: 'Bordsbokning', cat: 'operativ', desc: 'Online och manuell bordsreservation', longDesc: 'Online och manuell bordsreservation. Nyckelfunktioner: Bokningswidget, no-show-hantering, sittningsplanering, kapacitetsvy' },
      { slug: 'receptkalkyl', name: 'Receptkalkyl', cat: 'operativ', desc: 'Beräkna kostnad per rätt utifrån inköpspriser', longDesc: 'Beräkna kostnad per rätt utifrån inköpspriser. Nyckelfunktioner: Receptbyggare, portionskostnad, marginalkalkyl, prisändringsanalys' },
      { slug: 'personalschema', name: 'Personalschema', cat: 'operativ', desc: 'Schemalägg personal i skift', longDesc: 'Schemalägg personal i skift. Nyckelfunktioner: Skiftplanering, bytesförfrågningar, övertidsvarning, tillgänglighetsvy' },
      { slug: 'leverantorsbestallning', name: 'Leverantörsbeställning', cat: 'operativ', desc: 'Beställ varor direkt till leverantörer', longDesc: 'Beställ varor direkt till leverantörer. Nyckelfunktioner: Beställningsmallar, leveransbevakning, prishistorik' },
    ],
  },
  {
    slug: 'hotell', name: 'Hotell & Boende', icon: BedDouble,
    description: 'Rumsbokning, gäster & städschema',
    modules: [
      { slug: 'hotellkontoplan', name: 'Hotellkontoplan', cat: 'bokforing', desc: 'BAS-konton uppdelade per intäktstyp: rum, konferens, F&B', longDesc: 'BAS-konton uppdelade per intäktstyp: rum, konferens, F&B, tilläggstjänster. Nyckelfunktioner: Konton 3010 (rumsintäkter), 3020 (konferens), 3030 (F&B); auto-kontosättning' },
      { slug: 'momssplit-boende-tjanst', name: 'Momssplit boende/tjänst', cat: 'bokforing', desc: 'Moms 12% på boende, 25% på frukost, minibar, spa', longDesc: 'Moms 12% på boende, 25% på frukost, minibar, spa, parkering. Nyckelfunktioner: Automatisk split vid kombinationspaket (halvpension, konferenspaket), momsavstämning' },
      { slug: 'forskottsbetalning', name: 'Förskottsbetalning', cat: 'bokforing', desc: 'Bokför depositioner som förutbetald intäkt', longDesc: 'Bokför förskott/depositioner korrekt som förutbetald intäkt. Nyckelfunktioner: Konto 2420, automatisk intäktsföring vid incheckning, avbokningsbokföring' },
      { slug: 'provisionshantering', name: 'Provisionshantering', cat: 'bokforing', desc: 'Bokför provision till Booking.com, Expedia, Airbnb', longDesc: 'Bokför provision till Booking.com, Expedia, Airbnb som kostnad. Nyckelfunktioner: Provisionsberäkning per kanal, nettointäkt per bokning, konto 6090' },
      { slug: 'nattrevision', name: 'Nattrevision', cat: 'bokforing', desc: 'Automatiserad nattlig avstämning av dagens intäkter', longDesc: 'Automatiserad nattlig avstämning av dagens intäkter. Nyckelfunktioner: Dagsbokslut, kassaavstämning, no-show-debitering, verifikation per dygn' },
      { slug: 'revpar', name: 'RevPAR', cat: 'rapport', desc: 'Revenue Per Available Room', longDesc: 'Revenue per available room — branschens viktigaste KPI. Nyckelfunktioner: Beläggningsgrad × ADR, jämförelse per månad/säsong, budget vs utfall' },
      { slug: 'adr', name: 'ADR (Average Daily Rate)', cat: 'rapport', desc: 'Genomsnittlig rumspris', longDesc: 'Genomsnittlig rumspris. Nyckelfunktioner: Pris per rumstyp, kanalfördelning, säsongsanalys' },
      { slug: 'belaggningsgrad', name: 'Beläggningsgrad', cat: 'rapport', desc: 'Procent uthyrda rum', longDesc: 'Procent uthyrda rum. Nyckelfunktioner: Daglig/veckovis/månadsvis, prognos baserad på bokningsläge' },
      { slug: 'kanallonsamhet', name: 'Kanallönsamhet', cat: 'rapport', desc: 'Jämför nettointäkt per kanal efter provision', longDesc: 'Jämför nettointäkt per kanal efter provision. Nyckelfunktioner: Direktbokning vs OTA, provision %, rekommendation' },
      { slug: 'pms-import', name: 'PMS-import', cat: 'import', desc: 'Importera data från PMS (Mews, Protel, Hotellinx)', longDesc: 'Importera boknings- och intäktsdata från PMS (Mews, Protel, Hotellinx). Nyckelfunktioner: CSV/Excel, nattrevisionsrapport, auto-bokföring med momssplit' },
      { slug: 'channel-manager-rapport', name: 'Channel Manager-rapport', cat: 'import', desc: 'Importera provisionssammanställning per kanal', longDesc: 'Importera provisionssammanställning per kanal. Nyckelfunktioner: Booking/Expedia/Airbnb-rapporter, provisionsbokföring' },
      { slug: 'rumsbokning', name: 'Rumsbokning', cat: 'operativ', desc: 'Central bokningsmotor för rum och stugor', longDesc: 'Central bokningsmotor. Nyckelfunktioner: Kalendervy, tillgänglighet, säsongspriser, min/max-nätter' },
      { slug: 'gastregister', name: 'Gästregister', cat: 'operativ', desc: 'Gästprofiler och historik', longDesc: 'Gästprofiler och historik. Nyckelfunktioner: Kontaktuppgifter, besökshistorik, preferenser, GDPR' },
      { slug: 'stadschema', name: 'Städschema', cat: 'operativ', desc: 'Planera och följ upp städning per rum', longDesc: 'Planera städning per rum. Nyckelfunktioner: Status per rum, checklista, personalfördelning' },
      { slug: 'sasongsplanering', name: 'Säsongsplanering', cat: 'operativ', desc: 'Planera priser och kapacitet per säsong', longDesc: 'Priser och kapacitet per säsong. Nyckelfunktioner: Säsongsdefinition, dynamisk prissättning, beläggningsprognos' },
      { slug: 'gastkommunikation', name: 'Gästkommunikation', cat: 'operativ', desc: 'Automatiserad kommunikation med gäster', longDesc: 'Automatiska meddelanden. Nyckelfunktioner: Bekräftelse, incheckning, utcheckning, recensionsförfrågan' },
    ],
  },
  {
    slug: 'tech', name: 'Tech & IT', icon: Monitor,
    description: 'Projekthantering, tid & SLA',
    modules: [
      { slug: 'it-kontoplan', name: 'IT-kontoplan', cat: 'bokforing', desc: 'BAS-konton för konsult/SaaS-bolag', longDesc: 'BAS-konton anpassade för konsult/SaaS-bolag. Nyckelfunktioner: Konton för konsultintäkter, licensintäkter, SaaS MRR; auto-kontosättning' },
      { slug: 'projektredovisning', name: 'Projektredovisning', cat: 'bokforing', desc: 'Successiv vinstavräkning per kundprojekt', longDesc: 'Intäkter och kostnader per kundprojekt. Nyckelfunktioner: Successiv vinstavräkning, WIP-beräkning (konto 1470), projektbokslut' },
      { slug: 'fou-avdrag', name: 'FoU-avdrag', cat: 'bokforing', desc: 'Avdrag för forskning och utveckling', longDesc: 'Beräkna avdrag för forskning och utveckling. Nyckelfunktioner: Nedsättning av arbetsgivaravgifter, underlag per anställd, Skatteverket-krav' },
      { slug: 'licensavskrivning', name: 'Licensavskrivning', cat: 'bokforing', desc: 'Avskrivning av mjukvarulicenser och IP', longDesc: 'Hantera avskrivning av mjukvarulicenser och IP. Nyckelfunktioner: Avskrivningsplan, konto 1010/1020, linjär vs degressiv avskrivning' },
      { slug: 'eu-tjanstmoms', name: 'EU-tjänstemoms', cat: 'bokforing', desc: 'Omvänd skattskyldighet vid EU-försäljning', longDesc: 'Omvänd skattskyldighet vid försäljning till EU-kunder. Nyckelfunktioner: Automatisk B2B-kontroll (VAT-nummer), konto 2614, EU-försäljningsrapport' },
      { slug: 'debiteringsgrad', name: 'Debiteringsgrad', cat: 'rapport', desc: 'Andel debiterbara timmar av total arbetstid', longDesc: 'Andel debiterbara timmar av total arbetstid. Nyckelfunktioner: Per konsult/team, mål vs utfall, trend' },
      { slug: 'projektlonsamhet', name: 'Projektlönsamhet', cat: 'rapport', desc: 'Intäkt minus kostnad per projekt', longDesc: 'Intäkt minus kostnad per projekt. Nyckelfunktioner: Timkostnad vs debiterat, överdrag-varning, jämförelse budget' },
      { slug: 'mrr-arr', name: 'MRR/ARR', cat: 'rapport', desc: 'Monthly/Annual Recurring Revenue', longDesc: 'Monthly/Annual Recurring Revenue för SaaS. Nyckelfunktioner: Tillväxttakt, churn, expansion revenue' },
      { slug: 'tidrapport-import', name: 'Tidrapport-import', cat: 'import', desc: 'Importera från Harvest, Toggl, Clockify', longDesc: 'Importera tidrapporter från Harvest, Toggl, Clockify. Nyckelfunktioner: CSV/Excel, auto-koppling till projekt, fakturaunderlag' },
      { slug: 'projekthantering', name: 'Projekthantering', cat: 'operativ', desc: 'Överblick och styrning av kundprojekt', longDesc: 'Överblick och styrning av kundprojekt. Nyckelfunktioner: Projekttavla, milstolpar, tidslinje, budgetuppföljning' },
      { slug: 'tidrapportering', name: 'Tidrapportering', cat: 'operativ', desc: 'Logga tid per projekt och kund', longDesc: 'Logga tid per projekt och kund. Nyckelfunktioner: Timer, manuell inmatning, godkännandeflöde, debiterbara timmar' },
      { slug: 'arendehantering', name: 'Ärendehantering', cat: 'operativ', desc: 'Supportärenden och buggspårning', longDesc: 'Supportärenden och buggspårning. Nyckelfunktioner: Ärendekö, SLA-prioritet, statusflöde, kundportal' },
      { slug: 'resursplanering', name: 'Resursplanering', cat: 'operativ', desc: 'Allokera personal till projekt', longDesc: 'Allokera personal till projekt. Nyckelfunktioner: Beläggningsvy, kompetensfilter, överlappningsvarning' },
    ],
  },
  {
    slug: 'bygg', name: 'Bygg & Entreprenad', icon: HardHat,
    description: 'Projektkalkyler, underentreprenörer',
    modules: [
      { slug: 'byggkontoplan', name: 'Byggkontoplan', cat: 'bokforing', desc: 'BAS-konton med projektkontosättning och UE-konton', longDesc: 'BAS-konton med projektkontosättning och UE-konton. Nyckelfunktioner: Separata konton per projekt, UE-kostnader (konto 4400), materialkostnader' },
      { slug: 'omvand-skattskyldighet-bygg', name: 'Omvänd skattskyldighet bygg', cat: 'bokforing', desc: 'Omvänd moms vid UE-tjänster (6 kap. ML)', longDesc: 'Automatisk hantering av omvänd moms (6 kap. ML) vid UE-tjänster. Nyckelfunktioner: Automatisk kontroll köpare/säljare, fakturamärkning, momsdeklaration ruta 24' },
      { slug: 'rot-avdrag', name: 'ROT-avdrag', cat: 'bokforing', desc: 'ROT-avdrag per kund — 30% max 50 000 SEK', longDesc: 'Beräkna och rapportera ROT-avdrag per kund. Nyckelfunktioner: Automatisk 30%-beräkning, maxbelopp 50 000 SEK, personnummervalidering, Skatteverket-format' },
      { slug: 'successiv-vinstavrakning', name: 'Successiv vinstavräkning', cat: 'bokforing', desc: 'Periodisera intäkter efter färdigställandegrad', longDesc: 'Periodisera projektintäkter efter färdigställandegrad. Nyckelfunktioner: Beräkning av färdigställandegrad, intäktsperiodisering, konto 1470 WIP' },
      { slug: 'ue-attestering', name: 'UE-attestering', cat: 'bokforing', desc: 'Attestflöde för UE-fakturor med F-skatt-kontroll', longDesc: 'Attestflöde för underentreprenörsfakturor. Nyckelfunktioner: Godkännandeflöde, delavstämning, F-skatt-kontroll, försäkringsverifiering' },
      { slug: 'personalliggare-bygg', name: 'Personalliggare bygg', cat: 'bokforing', desc: 'Elektronisk personalliggare inkl. UE-personal', longDesc: 'Elektronisk personalliggare enligt Skatteverkets krav. Nyckelfunktioner: In/ut-registrering, export vid kontroll, UE-personal inkluderad' },
      { slug: 'ata-bokforing', name: 'ÄTA-bokföring', cat: 'bokforing', desc: 'Koppla ÄTA-arbeten till projekt och faktura', longDesc: 'Koppla ÄTA-arbeten till rätt projekt och faktura. Nyckelfunktioner: ÄTA-registrering, kostnadseffekt på projektkalkyl, intäktsökning vid godkänd ÄTA' },
      { slug: 'projektmarginal', name: 'Projektmarginal', cat: 'rapport', desc: 'Kalkylerad vs verklig marginal per projekt', longDesc: 'Kalkylerad vs verklig marginal per projekt. Nyckelfunktioner: Budget vs utfall, ÄTA-påverkan, UE-kostnad vs plan' },
      { slug: 'ata-analys', name: 'ÄTA-analys', cat: 'rapport', desc: 'ÄTA som andel av ursprunglig kalkyl', longDesc: 'ÄTA som andel av ursprunglig kalkyl. Nyckelfunktioner: ÄTA-andel per projekt, typ av ÄTA, kundgodkännandestatus' },
      { slug: 'likviditet-per-projekt', name: 'Likviditet per projekt', cat: 'rapport', desc: 'Kassaflöde per projekt', longDesc: 'Kassaflöde per projekt — fakturerat vs betalt vs kostnad. Nyckelfunktioner: Faktureringsrytm, kundfordringsålder, UE-skulder' },
      { slug: 'ue-fakturaimport', name: 'UE-fakturaimport', cat: 'import', desc: 'Importera underentreprenörsfakturor', longDesc: 'Importera underentreprenörsfakturor. Nyckelfunktioner: Parsning, projektkoppling, F-skatt-kontroll, auto-kontosättning' },
      { slug: 'materialkostnadsimport', name: 'Materialkostnadsimport', cat: 'import', desc: 'Importera materialinköp per projekt', longDesc: 'Importera materialinköp per projekt. Nyckelfunktioner: Leverantörsformat (Beijer, Ahlsell), projektfördelning' },
      { slug: 'projektkalkyl', name: 'Projektkalkyl', cat: 'operativ', desc: 'Detaljerade kalkyler inför anbud', longDesc: 'Detaljerade kalkyler inför anbud. Nyckelfunktioner: Arbete, material, maskiner, UE-kostnader, marginalpåslag' },
      { slug: 'ata-hantering', name: 'ÄTA-hantering', cat: 'operativ', desc: 'Spåra ändringar, tillägg och avgående', longDesc: 'Spåra ändringar, tillägg och avgående. Nyckelfunktioner: Registrering, kundgodkännande, koppling till faktura' },
      { slug: 'byggdagbok', name: 'Byggdagbok', cat: 'operativ', desc: 'Digital byggdagbok per projekt', longDesc: 'Digital dagbok per projekt. Nyckelfunktioner: Dagliga noteringar, foto, väderpåverkan, personallog' },
      { slug: 'ritningshantering', name: 'Ritningshantering', cat: 'operativ', desc: 'Versionshantering av projektritningar', longDesc: 'Versionshantering av projektritningar. Nyckelfunktioner: Uppladdning, versionsjämförelse, distribution till UE' },
      { slug: 'materialbestallning', name: 'Materialbeställning', cat: 'operativ', desc: 'Beställ och spåra material till projekt', longDesc: 'Beställ och spåra material. Nyckelfunktioner: Materiallistor, leveransbevakning, kostnadsuppföljning' },
    ],
  },
  {
    slug: 'halsa', name: 'Hälsa & Sjukvård', icon: HeartPulse,
    description: 'Patientbokning, journal & recept',
    modules: [
      { slug: 'vardkontoplan', name: 'Vårdkontoplan', cat: 'bokforing', desc: 'BAS-konton: region, privat, försäkring', longDesc: 'BAS-konton uppdelade per intäktstyp: regionavtal, privatpatienter, försäkring. Nyckelfunktioner: Konton 3010 (regionersättning), 3020 (patientavgift), 3030 (försäkring)' },
      { slug: 'momsfrihet-sjukvard', name: 'Momsfrihet sjukvård', cat: 'bokforing', desc: 'Momsfria vårdtjänster vs momspliktiga sidotjänster', longDesc: 'Hantera momsfria vårdtjänster vs momspliktiga sidotjänster. Nyckelfunktioner: Automatisk momsbedömning per tjänsttyp, korrekt moms vid blandad verksamhet' },
      { slug: 'forsakringsersattning', name: 'Försäkringsersättning', cat: 'bokforing', desc: 'Bokför försäkringsersättningar vid godkännande', longDesc: 'Bokför ersättningar från försäkringsbolag korrekt. Nyckelfunktioner: Intäktsföring vid godkännande, kundfordran per försäkringsbolag, avskrivning av nekade ärenden' },
      { slug: 'frikort-hogkostnadsskydd', name: 'Frikort & Högkostnadsskydd', cat: 'bokforing', desc: 'Patienters frikort vid avgiftsberäkning', longDesc: 'Hantera patienters frikort vid avgiftsberäkning. Nyckelfunktioner: Automatisk kontroll mot högkostnadsgräns, rapportering till region' },
      { slug: 'intakt-per-behandlare', name: 'Intäkt per behandlare', cat: 'rapport', desc: 'Omsättning fördelat per vårdgivare', longDesc: 'Omsättning fördelat per vårdgivare. Nyckelfunktioner: Per dag/vecka/månad, privatpatienter vs region, besökssnitt' },
      { slug: 'patientmix', name: 'Patientmix', cat: 'rapport', desc: 'Fördelning region/privat/försäkring', longDesc: 'Fördelning region/privat/försäkring. Nyckelfunktioner: Intäktsfördelning per betalarkategori, trend, lönsamhet per typ' },
      { slug: 'regionersattningsimport', name: 'Regionersättningsimport', cat: 'import', desc: 'Importera utbetalningsbesked från region', longDesc: 'Importera utbetalningsbesked från region. Nyckelfunktioner: Periodisering, kontosättning, avstämning mot avtal' },
      { slug: 'forsakringsrapport-import', name: 'Försäkringsrapport-import', cat: 'import', desc: 'Importera beslut från försäkringsbolag', longDesc: 'Importera beslut och utbetalningar från försäkringsbolag. Nyckelfunktioner: Auto-bokföring godkända/nekade ärenden' },
      { slug: 'patientbokning', name: 'Patientbokning', cat: 'operativ', desc: 'Bokning av besök och behandlingar', longDesc: 'Bokning av besök och behandlingar. Nyckelfunktioner: Onlinebokning, kalendervy, SMS-påminnelse, väntelista' },
      { slug: 'journalhantering', name: 'Journalhantering', cat: 'operativ', desc: 'Strukturerade patientjournaler', longDesc: 'Strukturerade patientjournaler. Nyckelfunktioner: Anteckningar, diagnoser, vårdplan, GDPR-efterlevnad' },
      { slug: 'remisshantering', name: 'Remisshantering', cat: 'operativ', desc: 'Skicka och ta emot remisser', longDesc: 'Skicka och ta emot remisser. Nyckelfunktioner: Mallar, statusspårning, svarsbevakning' },
      { slug: 'kassasystem-patientavgifter', name: 'Kassasystem & Patientavgifter', cat: 'operativ', desc: 'Debitera patientbetalningar', longDesc: 'Debitera patientbetalningar. Nyckelfunktioner: Avgiftskategorier, frikort-koll, kortbetalning' },
    ],
  },
  {
    slug: 'detaljhandel', name: 'Detaljhandel', icon: Store,
    description: 'Lager, kassa & leverantörer',
    modules: [
      { slug: 'detaljhandelskontoplan', name: 'Detaljhandelskontoplan', cat: 'bokforing', desc: 'BAS-konton per produktkategori och momssats', longDesc: 'BAS-konton per produktkategori och momssats. Nyckelfunktioner: Intäktskonton per varugrupp, separata konton 25%/12%/6% moms' },
      { slug: 'lagervardering', name: 'Lagervärdering', cat: 'bokforing', desc: 'FIFO och vägt genomsnitt för bokslut', longDesc: 'Löpande beräkning av lagervärde för bokslut. Nyckelfunktioner: FIFO och vägt genomsnitt, månadsbokslut, inkuransbedömning, konto 1400' },
      { slug: 'kassaavstamning-butik', name: 'Kassaavstämning butik', cat: 'bokforing', desc: 'Daglig avstämning kassa vs kassarapport', longDesc: 'Daglig avstämning kassa vs kassarapport. Nyckelfunktioner: Z-rapport-import, avvikelse, kontant/kort-split, verifikation per dag' },
      { slug: 'svinnbokforing', name: 'Svinnbokföring', cat: 'bokforing', desc: 'Bokför varusvinn som kostnad (konto 4730)', longDesc: 'Bokför varusvinn korrekt som kostnad. Nyckelfunktioner: Svinnregistrering, konto 4730, period-uppföljning' },
      { slug: 'personalliggare-butik', name: 'Personalliggare butik', cat: 'bokforing', desc: 'Personalliggare för livsmedelsbutik', longDesc: 'Elektronisk personalliggare (obligatorisk livsmedelsbutik). Nyckelfunktioner: In/ut-registrering, Skatteverket-export' },
      { slug: 'bruttomarginal-per-varugrupp', name: 'Bruttomarginal per varugrupp', cat: 'rapport', desc: 'Inpris vs utpris per kategori', longDesc: 'Inpris vs utpris per kategori. Nyckelfunktioner: Marginal %, jämförelse kampanjperiod vs normal, trendvy' },
      { slug: 'lageromsattningshastighet', name: 'Lageromsättningshastighet', cat: 'rapport', desc: 'Hur snabbt lagret omsätts', longDesc: 'Hur snabbt lagret omsätts. Nyckelfunktioner: Per varugrupp, kapitalbindning, beställningspunkt-förslag' },
      { slug: 'svinnprocent', name: 'Svinnprocent', cat: 'rapport', desc: 'Svinn i kronor och procent', longDesc: 'Svinn i kronor och procent av omsättning. Nyckelfunktioner: Per kategori, trend, benchmark mot branschsnitt' },
      { slug: 'forsaljning-per-m2', name: 'Försäljning per m²', cat: 'rapport', desc: 'Butikseffektivitet', longDesc: 'Butikseffektivitet. Nyckelfunktioner: Intäkt per kvadratmeter, jämförelse butiker' },
      { slug: 'pos-z-rapport-import', name: 'POS Z-rapport-import', cat: 'import', desc: 'Dagskassarapport från kassasystem', longDesc: 'Dagskassarapport från kassasystem. Nyckelfunktioner: CSV/Excel från iZettle, Sitoo, Caspeco; auto-kontosättning med momssplit' },
      { slug: 'inventeringsimport', name: 'Inventeringsimport', cat: 'import', desc: 'Importera inventeringsresultat', longDesc: 'Importera inventeringsresultat. Nyckelfunktioner: Avvikelseberäkning, lageruppdatering, svinnbokföring' },
      { slug: 'leverantorsfaktura-import-butik', name: 'Leverantörsfaktura-import', cat: 'import', desc: 'Importera leverantörsfakturor', longDesc: 'Importera leverantörsfakturor. Nyckelfunktioner: Parsning, inprisuppdatering, auto-kontosättning' },
      { slug: 'lagerhantering', name: 'Lagerhantering', cat: 'operativ', desc: 'Lagernivåer och rörelser', longDesc: 'Lagernivåer och rörelser. Nyckelfunktioner: Inleverans, bristlista, beställningspunkt, lagerplatser' },
      { slug: 'kampanjer-rabatter', name: 'Kampanjer & Rabatter', cat: 'operativ', desc: 'Priskampanjer och erbjudanden', longDesc: 'Priskampanjer och erbjudanden. Nyckelfunktioner: Rabattregler, tidsbegränsade kampanjer, marginalbevakning' },
      { slug: 'kundklubb', name: 'Kundklubb', cat: 'operativ', desc: 'Lojalitetsprogram med poäng', longDesc: 'Lojalitetsprogram. Nyckelfunktioner: Poängintjäning, belöningar, riktade kampanjer' },
      { slug: 'prishantering', name: 'Prishantering', cat: 'operativ', desc: 'Prissättning med marginalbevakning', longDesc: 'Centraliserad prissättning. Nyckelfunktioner: Inpris vs utpris, marginalkalkyl, prisändringslogg' },
      { slug: 'butiksdrift-schema', name: 'Butiksdrift & Schema', cat: 'operativ', desc: 'Bemanning och öppettider', longDesc: 'Bemanning och öppettider. Nyckelfunktioner: Schemaläggning, timrapport, budgetjämförelse' },
    ],
  },
  {
    slug: 'ehandel', name: 'E-handel', icon: ShoppingCart,
    description: 'Ordrar, frakt & returer',
    modules: [
      { slug: 'ehandelskontoplan', name: 'E-handelskontoplan', cat: 'bokforing', desc: 'BAS-konton för order, frakt, returer, avgifter', longDesc: 'BAS-konton för orderintäkter, fraktintäkt, returer, plattformsavgifter. Nyckelfunktioner: Konton 3001 (varuförsäljning), 3540 (fraktintäkt), 3740 (returkostnad), 6590 (plattformsavgift)' },
      { slug: 'lagervardering-ehandel', name: 'Lagervärdering', cat: 'bokforing', desc: 'FIFO/vägt genomsnitt för e-handel', longDesc: 'Löpande lagervärde för bokslut. Nyckelfunktioner: FIFO, vägt genomsnitt, månadsbokslut, inkuransbedömning' },
      { slug: 'returbokforing', name: 'Returbokföring', cat: 'bokforing', desc: 'Automatisk kreditering vid returer', longDesc: 'Automatisk kreditering vid returer. Nyckelfunktioner: Lageråterföring, konto 3740, momskorrigering, periodsummering' },
      { slug: 'multi-currency', name: 'Multi-currency', cat: 'bokforing', desc: 'Bokför utländsk valuta i SEK', longDesc: 'Bokför försäljning i utländsk valuta i SEK. Nyckelfunktioner: Valutaomvandling via Riksbanken-kurs, kursdifferens konto 3960/7960' },
      { slug: 'eu-moms-oss', name: 'EU-moms (OSS)', cat: 'bokforing', desc: 'One Stop Shop för EU-distansförsäljning', longDesc: 'One Stop Shop för moms vid EU-distansförsäljning. Nyckelfunktioner: Moms per destinationsland, OSS-deklarationsunderlag, tröskelvärdebevakning' },
      { slug: 'plattformsavgifter', name: 'Plattformsavgifter', cat: 'bokforing', desc: 'Bokför Shopify/Stripe/Klarna-avgifter', longDesc: 'Bokför avgifter från Shopify, Stripe, Klarna korrekt. Nyckelfunktioner: Bruttoförsäljning → avgift → nettoutbetalning, periodisering' },
      { slug: 'returprocent', name: 'Returprocent', cat: 'rapport', desc: 'Returer som andel av försäljning', longDesc: 'Returer som andel av försäljning. Nyckelfunktioner: Per produktkategori, kostnad per retur, trend' },
      { slug: 'genomsnittligt-ordervarde', name: 'Genomsnittligt ordervärde', cat: 'rapport', desc: 'Snittorder i kronor', longDesc: 'Snittorder i kronor. Nyckelfunktioner: Trend, kanalfördelning, kampanjeffekt' },
      { slug: 'kanalfordelning', name: 'Kanalfördelning', cat: 'rapport', desc: 'Intäkt per försäljningskanal', longDesc: 'Intäkt per försäljningskanal. Nyckelfunktioner: Egen webb vs marknadsplats, marginal per kanal' },
      { slug: 'fraktkostnad-vs-intakt', name: 'Fraktkostnad vs intäkt', cat: 'rapport', desc: 'Fraktnetto per order', longDesc: 'Fraktnetto per order. Nyckelfunktioner: Fraktsubvention, break-even-analys' },
      { slug: 'shopify-woo-import', name: 'Shopify/Woo-import', cat: 'import', desc: 'Importera ordrar från Shopify/WooCommerce', longDesc: 'Importera ordrar och utbetalningsrapporter. Nyckelfunktioner: CSV-export, auto-bokföring per order inkl. moms, frakt, rabatter' },
      { slug: 'klarna-rapport-import', name: 'Klarna-rapport-import', cat: 'import', desc: 'Importera Klarna-utbetalningar', longDesc: 'Importera Klarna-utbetalningar och avgifter. Nyckelfunktioner: Bruttobelopp, avgiftsavdrag, nettoutbetalning, periodmatchning' },
      { slug: 'fraktrapport-import', name: 'Fraktrapport-import', cat: 'import', desc: 'Importera fraktkostnader per order', longDesc: 'Importera fraktkostnader per order. Nyckelfunktioner: Postnord/DHL/Budbee-rapporter, kostnadsfördelning' },
      { slug: 'orderhantering', name: 'Orderhantering', cat: 'operativ', desc: 'Central ordervy från alla kanaler', longDesc: 'Central ordervy. Nyckelfunktioner: Orderstatus, plocklista, batch-hantering' },
      { slug: 'frakthantering', name: 'Frakthantering', cat: 'operativ', desc: 'Hantera frakt med transportörer', longDesc: 'Hantera frakt. Nyckelfunktioner: Fraktsedlar, spårning, returlogistik' },
      { slug: 'returhantering-operativ', name: 'Returhantering', cat: 'operativ', desc: 'Hantera returer och byten', longDesc: 'Hantera returer och byten. Nyckelfunktioner: Returgodkännande, lageråterföring, återbetalning' },
      { slug: 'produktdatahantering', name: 'Produktdatahantering', cat: 'operativ', desc: 'Central produktinformation', longDesc: 'Central produktinfo. Nyckelfunktioner: Beskrivningar, bilder, attribut' },
    ],
  },
  {
    slug: 'frisor', name: 'Frisör & Skönhet', icon: Scissors,
    description: 'Tidsbokning, kunder & produkter',
    modules: [
      { slug: 'salongkontoplan', name: 'Salongkontoplan', cat: 'bokforing', desc: 'BAS-konton: behandling, produktförsäljning, presentkort', longDesc: 'BAS-konton uppdelade: tjänsteintäkter, produktförsäljning, presentkort. Nyckelfunktioner: Konton 3010 (behandling), 3020 (produktförsäljning), 2420 (presentkortsskuld)' },
      { slug: 'provisionsberakning', name: 'Provisionsberäkning', cat: 'bokforing', desc: 'Provision per frisör/terapeut som lönekostnad', longDesc: 'Räkna provision per frisör/terapeut och bokför som lönekostnad. Nyckelfunktioner: Procent på tjänst/produkt, trappsteg, konto 7010/7210, månadssammanställning' },
      { slug: 'presentkort-som-skuld', name: 'Presentkort som skuld', cat: 'bokforing', desc: 'Presentkort som förutbetald intäkt', longDesc: 'Bokför sålda presentkort som förutbetald intäkt tills inlösen. Nyckelfunktioner: Konto 2420 (skuld), intäktsföring vid inlösen, förfallohantering' },
      { slug: 'kassaavstamning-salong', name: 'Kassaavstämning salong', cat: 'bokforing', desc: 'Daglig avstämning kort/Swish/kontant', longDesc: 'Daglig avstämning kort/Swish/kontant. Nyckelfunktioner: Z-rapport, avvikelse, verifikation per dag' },
      { slug: 'personalliggare-salong', name: 'Personalliggare salong', cat: 'bokforing', desc: 'Personalliggare enligt Skatteverket', longDesc: 'Elektronisk personalliggare enligt Skatteverket. Nyckelfunktioner: In/ut-registrering, export vid kontroll' },
      { slug: 'intakt-per-stol', name: 'Intäkt per stol', cat: 'rapport', desc: 'Omsättning per arbetsstation', longDesc: 'Omsättning per arbetsstation. Nyckelfunktioner: Per dag/vecka, beläggningsgrad, optimeringsförslag' },
      { slug: 'provisionsandel', name: 'Provisionsandel', cat: 'rapport', desc: 'Provisionskostnad som andel av intäkt', longDesc: 'Provisionskostnad som andel av tjänsteintäkt. Nyckelfunktioner: Per frisör, trend, lönsamhet per anställd' },
      { slug: 'produktforsaljning-per-besok', name: 'Produktförsäljning per besök', cat: 'rapport', desc: 'Merförsäljning av produkter', longDesc: 'Merförsäljning av produkter. Nyckelfunktioner: Snitt per kund, andel av omsättning' },
      { slug: 'kassarapport-import-salong', name: 'Kassarapport-import', cat: 'import', desc: 'Importera dagskassa från iZettle', longDesc: 'Importera dagskassa från kassasystem. Nyckelfunktioner: CSV från iZettle/Zettle, auto-kontosättning' },
      { slug: 'bokningssystem-import', name: 'Bokningssystem-import', cat: 'import', desc: 'Importera från Timma, Fresha, Planway', longDesc: 'Importera bokningsdata och intäkter. Nyckelfunktioner: Export från Timma, Fresha, Planway; intäktsfördelning per behandlare' },
      { slug: 'tidsbokning', name: 'Tidsbokning', cat: 'operativ', desc: 'Online och receptionsbokning', longDesc: 'Online och receptionsbokning. Nyckelfunktioner: Bokningswidget, SMS-påminnelse, väntelista' },
      { slug: 'kundkort', name: 'Kundkort', cat: 'operativ', desc: 'Profil med behandlingshistorik', longDesc: 'Profil med behandlingshistorik. Nyckelfunktioner: Favoritbehandlare, allergier, färgrecept' },
      { slug: 'sms-paminnelser', name: 'SMS-påminnelser', cat: 'operativ', desc: 'Automatiska bokningspåminnelser', longDesc: 'Automatiska påminnelser. Nyckelfunktioner: Bokningspåminnelse, återbesökspåminnelse' },
      { slug: 'skiftschema-salong', name: 'Skiftschema', cat: 'operativ', desc: 'Schemalägg personal med stolsfördelning', longDesc: 'Schemalägg personal. Nyckelfunktioner: Stolsfördelning, ledighetsönskemål' },
    ],
  },
  {
    slug: 'transport', name: 'Transport & Logistik', icon: Truck,
    description: 'Flotta, rutter & leveranser',
    modules: [
      { slug: 'transportkontoplan', name: 'Transportkontoplan', cat: 'bokforing', desc: 'BAS-konton: bränsle, leasing, underhåll, försäkring', longDesc: 'BAS-konton per kostnadskategori: bränsle, leasing, underhåll, försäkring. Nyckelfunktioner: Konton per fordon möjligt, kostnadskonton 5610/5620/5611/5612' },
      { slug: 'fordonsavskrivning', name: 'Fordonsavskrivning', cat: 'bokforing', desc: 'Avskrivning per fordon (räkenskapsenlig)', longDesc: 'Hantera avskrivning per fordon. Nyckelfunktioner: Linjär/degressiv, räkenskapsenlig avskrivning, konto 1240/7832' },
      { slug: 'leasinghantering', name: 'Leasinghantering', cat: 'bokforing', desc: 'Operationell vs finansiell leasing', longDesc: 'Bokför leasing korrekt (operationell vs finansiell). Nyckelfunktioner: Leasingavgift som driftskostnad, restvärde, avtalsperiod' },
      { slug: 'trangselskatt', name: 'Trängselskatt', cat: 'bokforing', desc: 'Avdragsgill kostnad (konto 5615)', longDesc: 'Bokför trängselskatt som avdragsgill kostnad. Nyckelfunktioner: Auto-kontosättning konto 5615, per fordon, periodsammanställning' },
      { slug: 'milersattning-vs-faktisk-kostnad', name: 'Milersättning vs faktisk kostnad', cat: 'bokforing', desc: 'Jämför schablon (25 kr/mil) mot verklig kostnad', longDesc: 'Jämför schablon (25 kr/mil) mot verklig fordonskostnad. Nyckelfunktioner: Per fordon, rekommendation avdragsmetod, Skatteverket-schabloner' },
      { slug: 'kostnad-per-mil', name: 'Kostnad per mil', cat: 'rapport', desc: 'Total driftskostnad per mil och fordon', longDesc: 'Total driftskostnad per mil och per fordon. Nyckelfunktioner: Bränsle + underhåll + avskrivning + försäkring, trend' },
      { slug: 'intakt-per-fordon', name: 'Intäkt per fordon', cat: 'rapport', desc: 'Omsättning fördelad per fordon', longDesc: 'Omsättning fördelad per fordon. Nyckelfunktioner: Lönsamhet per fordon, underutnyttjade resurser' },
      { slug: 'bransleeffektivitet', name: 'Bränsleeffektivitet', cat: 'rapport', desc: 'Bränsleförbrukning per fordon', longDesc: 'Bränsleförbrukning per fordon och period. Nyckelfunktioner: Liter/mil, trend, avvikelse mot förväntat' },
      { slug: 'branslekort-import', name: 'Bränslekort-import', cat: 'import', desc: 'Importera tankningar (Circle K, OKQ8, Preem)', longDesc: 'Importera tankningar från bränslekort (Circle K, OKQ8, Preem). Nyckelfunktioner: CSV, auto-kontosättning per fordon' },
      { slug: 'vagtulls-import', name: 'Vägtulls-import', cat: 'import', desc: 'Importera trängselskatt (Transportstyrelsen)', longDesc: 'Importera trängselskatt och broavgifter. Nyckelfunktioner: Transportstyrelsen-format, auto-kontosättning' },
      { slug: 'flottahantering', name: 'Flottahantering', cat: 'operativ', desc: 'Fordonsregister och översikt', longDesc: 'Fordonsregister och översikt. Nyckelfunktioner: Besiktning, försäkring, leasingperioder' },
      { slug: 'ruttplanering', name: 'Ruttplanering', cat: 'operativ', desc: 'Optimera körrutter', longDesc: 'Optimera körrutter. Nyckelfunktioner: Adressklustring, tidsestimering, kapacitet' },
      { slug: 'leveranssparning', name: 'Leveransspårning', cat: 'operativ', desc: 'Realtidsspårning av leveranser', longDesc: 'Realtidsspårning av leveranser. Nyckelfunktioner: GPS, ETA, leveransbevis, kundnotifiering' },
      { slug: 'fordonsunderhall', name: 'Fordonsunderhåll', cat: 'operativ', desc: 'Planera service och reparationer', longDesc: 'Planera service och reparationer. Nyckelfunktioner: Serviceintervall, reservdelshistorik' },
      { slug: 'chauforshantering', name: 'Chaufförshantering', cat: 'operativ', desc: 'Personal- och behörighetsregister', longDesc: 'Personal och behörigheter. Nyckelfunktioner: Körkortsklass, YKB, timrapport' },
      { slug: 'fraktsedlar-dokument', name: 'Fraktsedlar & Dokument', cat: 'operativ', desc: 'Generera fraktdokument', longDesc: 'Generera fraktdokument. Nyckelfunktioner: CMR, följesedel, digital signatur' },
    ],
  },
  {
    slug: 'juridik', name: 'Juridik & Redovisning', icon: Scale,
    description: 'Ärenden, tidrapport & klienter',
    modules: [
      { slug: 'juristkontoplan', name: 'Juristkontoplan', cat: 'bokforing', desc: 'BAS-konton: arvoden, klientmedel, utlägg', longDesc: 'BAS-konton för arvodesintäkter, klientmedel, utlägg. Nyckelfunktioner: Konton 3010 (arvoden), 1690 (klientmedel i förvaltning), 6990 (utlägg för klients räkning)' },
      { slug: 'klientmedelskonto', name: 'Klientmedelskonto', cat: 'bokforing', desc: 'Separat hantering av klientmedel', longDesc: 'Separat hantering av klientmedel (disciplinnämndsregler). Nyckelfunktioner: Konto 1690/2890, klientmedelslista, avstämning mot bankkonto, rapportering' },
      { slug: 'wip-vardering', name: 'WIP-värdering', cat: 'bokforing', desc: 'Pågående arbete ej fakturerat', longDesc: 'Värdera pågående arbete (nedlagd tid ej fakturerad). Nyckelfunktioner: Beräkning av WIP, konto 1470, månatlig omvärdering' },
      { slug: 'a-conto-bokforing', name: 'A conto-bokföring', cat: 'bokforing', desc: 'A conto-fakturor och slutavräkning', longDesc: 'Bokför a conto-fakturor och slutavräkning. Nyckelfunktioner: Förskottsbokföring konto 2420, avräkning vid slutfaktura' },
      { slug: 'debiteringsgrad-juridik', name: 'Debiteringsgrad', cat: 'rapport', desc: 'Debiterbara timmar av total arbetstid', longDesc: 'Andel debiterbara timmar av total arbetstid. Nyckelfunktioner: Per jurist/konsult, mål vs utfall, trend' },
      { slug: 'realisationsgrad', name: 'Realisationsgrad', cat: 'rapport', desc: 'Fakturerat vs tidvärde', longDesc: 'Fakturerat belopp vs tidvärde (nedskrivning av tid). Nyckelfunktioner: Per ärende, mönsteranalys, lönsamhet per ärendetyp' },
      { slug: 'genomsnittlig-timintakt', name: 'Genomsnittlig timintäkt', cat: 'rapport', desc: 'Faktiskt fakturerat per timme', longDesc: 'Faktiskt fakturerat per timme. Nyckelfunktioner: Per jurist, klient, ärendetyp; jämförelse mot prislista' },
      { slug: 'wip-rapport', name: 'WIP-rapport', cat: 'rapport', desc: 'Pågående arbete med åldringsanalys', longDesc: 'Totalt pågående arbete ej fakturerat. Nyckelfunktioner: Per klient/ärende, åldringsanalys, risk för nedskrivning' },
      { slug: 'tidrapport-import-juridik', name: 'Tidrapport-import', cat: 'import', desc: 'Importera från Clio, Maconomy', longDesc: 'Importera tid från ärendehanteringssystem. Nyckelfunktioner: CSV från Time, Clio, Maconomy; koppling till ärende och klient' },
      { slug: 'arendehantering-juridik', name: 'Ärendehantering', cat: 'operativ', desc: 'Administrera klientärenden', longDesc: 'Administrera klientärenden. Nyckelfunktioner: Ärendetyper, statusflöde, deadline-bevakning' },
      { slug: 'tidrapportering-juridik', name: 'Tidrapportering', cat: 'operativ', desc: 'Registrera tid per ärende', longDesc: 'Registrera tid per ärende. Nyckelfunktioner: Debiterbara vs interna timmar, godkännande' },
      { slug: 'dokumenthantering', name: 'Dokumenthantering', cat: 'operativ', desc: 'Versionshanterade dokument', longDesc: 'Versionshanterade dokument per ärende. Nyckelfunktioner: Mallbibliotek, e-signering, klientdelning' },
      { slug: 'deadlinebevakning', name: 'Deadlinebevakning', cat: 'operativ', desc: 'Påminnelser för tidsfrister', longDesc: 'Påminnelser för tidsfrister. Nyckelfunktioner: Preskriptionstider, eskaleringsregler' },
      { slug: 'intressekonfliktskontroll', name: 'Intressekonfliktskontroll', cat: 'operativ', desc: 'Kontrollera jäv vid nya ärenden', longDesc: 'Kontrollera jäv vid nya ärenden. Nyckelfunktioner: Partsregister, automatisk sökning, logg' },
    ],
  },
  {
    slug: 'utbildning', name: 'Utbildning & Förskola', icon: GraduationCap,
    description: 'Schema, elever & närvaro',
    modules: [
      { slug: 'utbildningskontoplan', name: 'Utbildningskontoplan', cat: 'bokforing', desc: 'BAS-konton: kommunal peng, avgift, statsbidrag', longDesc: 'BAS-konton för kommunal peng, statsbidrag, föräldraavgift. Nyckelfunktioner: Konton 3010 (kommunal ersättning), 3020 (föräldraavgift), 3910 (statsbidrag)' },
      { slug: 'maxtaxa-fakturering', name: 'Maxtaxa-fakturering', cat: 'bokforing', desc: 'Avgift enligt maxtaxa-reglerna', longDesc: 'Automatisk beräkning av avgift enligt maxtaxa-reglerna. Nyckelfunktioner: Inkomstkontroll, syskonrabatt, schema-avdrag, frånvaroavdrag' },
      { slug: 'statsbidragsperiodisering', name: 'Statsbidragsperiodisering', cat: 'bokforing', desc: 'Periodisera statsbidrag korrekt', longDesc: 'Periodisera statsbidrag korrekt över den period de avser. Nyckelfunktioner: Konto 2970 (förutbetald intäkt), villkorsuppfyllnad, återbetalningsrisk' },
      { slug: 'momsfrihet-utbildning', name: 'Momsfrihet utbildning', cat: 'bokforing', desc: 'Momsfria utbildningstjänster', longDesc: 'Utbildningstjänster är momsfria. Nyckelfunktioner: Korrekt momsbedömning, sidoverksamhet (cafeteria, uthyrning) kan vara momspliktig' },
      { slug: 'kostnad-per-barn-elev', name: 'Kostnad per barn/elev', cat: 'rapport', desc: 'Driftskostnad per inskrivet barn', longDesc: 'Total driftskostnad per inskrivet barn. Nyckelfunktioner: Personal, lokal, mat, material; jämförelse med kommunal peng' },
      { slug: 'personaltathet', name: 'Personaltäthet', cat: 'rapport', desc: 'Antal barn per heltidsanställd', longDesc: 'Antal barn per heltidsanställd. Nyckelfunktioner: Trend, lagkrav (förskolans riktlinje), schemaanalys' },
      { slug: 'kommunal-peng-import', name: 'Kommunal peng-import', cat: 'import', desc: 'Importera utbetalningsbesked', longDesc: 'Importera utbetalningsbesked från kommun. Nyckelfunktioner: Periodisering, kontosättning, avstämning' },
      { slug: 'schemalaeggning', name: 'Schemaläggning', cat: 'operativ', desc: 'Bygg undervisningsschema', longDesc: 'Undervisningsschema. Nyckelfunktioner: Per klass/lärare/sal, konfliktkontroll' },
      { slug: 'elevregister', name: 'Elevregister', cat: 'operativ', desc: 'Elev- och barnuppgifter', longDesc: 'Elev- och barnuppgifter. Nyckelfunktioner: Kontakt, vårdnadshavare, allergi, specialbehov' },
      { slug: 'narvarohantering', name: 'Närvarohantering', cat: 'operativ', desc: 'Registrera frånvaro', longDesc: 'Registrera frånvaro. Nyckelfunktioner: Daglig närvaro, mönsteranalys, föräldraavisering' },
      { slug: 'foraldrakommunikation', name: 'Föräldrakommunikation', cat: 'operativ', desc: 'Meddelanden till vårdnadshavare', longDesc: 'Meddelanden till vårdnadshavare. Nyckelfunktioner: Push/e-post/SMS, nyhetsflöde' },
      { slug: 'matsedel-allergikost', name: 'Matsedel & Allergikost', cat: 'operativ', desc: 'Publicera matsedel', longDesc: 'Publicera matsedel. Nyckelfunktioner: Veckomatsdel, allergiflaggor' },
      { slug: 'vikariebokning', name: 'Vikariebokning', cat: 'operativ', desc: 'Hantera vikarier', longDesc: 'Hantera vikarier. Nyckelfunktioner: Vikariepool, snabbbokning, kostnadsspårning' },
    ],
  },
  {
    slug: 'jordbruk', name: 'Jordbruk & Livsmedel', icon: Wheat,
    description: 'Skörd, djurhållning & spårbarhet',
    modules: [
      { slug: 'jordbrukskontoplan', name: 'Jordbrukskontoplan', cat: 'bokforing', desc: 'BAS-konton: gröda, djur, skog, EU-stöd', longDesc: 'BAS-konton anpassade för gröda, djur, skogsbruk, EU-stöd. Nyckelfunktioner: Konton 3010 (växtodling), 3020 (djurförsäljning), 3910 (EU-stöd), 1280 (biologiska tillgångar)' },
      { slug: 'skogskonto', name: 'Skogskonto', cat: 'bokforing', desc: 'Insättning/uttag skogskonto (max 60%)', longDesc: 'Hantera insättning och uttag från skogskonto. Nyckelfunktioner: Insättning (max 60% av skogsintäkt), beskattning vid uttag, konto 1760' },
      { slug: 'expansionsfond', name: 'Expansionsfond', cat: 'bokforing', desc: 'Avsättning för enskild firma (20.6% skatt)', longDesc: 'Beräkna avsättning till expansionsfond för enskild firma. Nyckelfunktioner: Beräkning av underlag, expansionsfondsskatt 20,6%, NE-bilaga' },
      { slug: 'rantefordelning', name: 'Räntefördelning', cat: 'bokforing', desc: 'Positiv/negativ räntefördelning', longDesc: 'Positiv/negativ räntefördelning på kapital. Nyckelfunktioner: Kapitalunderlag, statslåneränta, inkomstfördelning tjänst/kapital' },
      { slug: 'eu-stod-som-intakt', name: 'EU-stöd som intäkt', cat: 'bokforing', desc: 'Periodisera EU-jordbruksstöd', longDesc: 'Periodisera EU-jordbruksstöd korrekt. Nyckelfunktioner: Intäktsföring per period, villkorsskuld, jämförelse ansökt vs utbetalt' },
      { slug: 'biologiska-tillgangar', name: 'Biologiska tillgångar', cat: 'bokforing', desc: 'Värdera djur och grödor', longDesc: 'Värdera djur och grödor som tillgång. Nyckelfunktioner: Anskaffningsvärde vs verkligt värde, konto 1280, årlig omvärdering' },
      { slug: 'momssplit-livsmedel', name: 'Momssplit livsmedel', cat: 'bokforing', desc: 'Moms 12% livsmedel, 25% övrigt', longDesc: 'Moms 12% vid livsmedelsförsäljning, 25% övriga varor. Nyckelfunktioner: Automatisk momskod per produkttyp' },
      { slug: 'avkastning-per-hektar', name: 'Avkastning per hektar', cat: 'rapport', desc: 'Intäkt minus kostnad per yta', longDesc: 'Intäkt minus kostnad per odlad yta. Nyckelfunktioner: Per gröda, säsongsjämförelse, vädereffekt' },
      { slug: 'bidragsberoende', name: 'Bidragsberoende', cat: 'rapport', desc: 'EU-stöd som andel av intäkt', longDesc: 'EU-stöd som andel av total intäkt. Nyckelfunktioner: Trend, risk vid policyändring' },
      { slug: 'djurkostnad-per-enhet', name: 'Djurkostnad per enhet', cat: 'rapport', desc: 'Total kostnad per djur', longDesc: 'Total kostnad per djur (foder, veterinär, stall). Nyckelfunktioner: Per djurtyp, jämförelse med intäkt vid slakt/försäljning' },
      { slug: 'sam-utbetalningsimport', name: 'SAM-utbetalningsimport', cat: 'import', desc: 'Importera EU-stödutbetalningar', longDesc: 'Importera utbetalningsbesked för EU-jordbruksstöd. Nyckelfunktioner: Jordbruksverket-format, periodisering, auto-kontosättning' },
      { slug: 'skordeplanering', name: 'Skördeplanering', cat: 'operativ', desc: 'Planera odlingscykler', longDesc: 'Planera odlingscykler. Nyckelfunktioner: Fältregister, grödor, sådd/skörd-datum' },
      { slug: 'djurhallning', name: 'Djurhållning', cat: 'operativ', desc: 'Register och uppföljning', longDesc: 'Register och uppföljning av besättning. Nyckelfunktioner: Individregister, hälsologg, Jordbruksverket-rapportering' },
      { slug: 'sparbarhet', name: 'Spårbarhet', cat: 'operativ', desc: 'Spåra livsmedel från jord till bord', longDesc: 'Spåra livsmedel från jord till bord. Nyckelfunktioner: Batchnummer, leveranskedja, återkallning' },
      { slug: 'maskinlogg', name: 'Maskinlogg', cat: 'operativ', desc: 'Drifttid och underhåll', longDesc: 'Drifttid och underhåll. Nyckelfunktioner: Maskinregister, timlogg, servicepåminnelse' },
      { slug: 'certifieringar', name: 'Certifieringar', cat: 'operativ', desc: 'KRAV, ekologisk certifiering', longDesc: 'KRAV, ekologisk, EU-ekologisk. Nyckelfunktioner: Certifikatregister, giltighetstid, revisionsförberedelse' },
    ],
  },
  {
    slug: 'media', name: 'Media & Kommunikation', icon: Film,
    description: 'Projekt, innehåll & publicering',
    modules: [
      { slug: 'mediakontoplan', name: 'Mediakontoplan', cat: 'bokforing', desc: 'BAS-konton: projekt, licens, royalty', longDesc: 'BAS-konton per intäktstyp: projektarvoden, licensintäkt, royalties. Nyckelfunktioner: Konton 3010 (projektintäkt), 3020 (licensintäkt), 3910 (royalty)' },
      { slug: 'projektredovisning-media', name: 'Projektredovisning', cat: 'bokforing', desc: 'Intäkter och kostnader per kundprojekt', longDesc: 'Intäkter och kostnader per kundprojekt. Nyckelfunktioner: Budget vs utfall, WIP vid pågående projekt, projektbokslut' },
      { slug: 'freelancer-bokforing', name: 'Freelancer-bokföring', cat: 'bokforing', desc: 'Frilansarfakturor med F-skatt-kontroll', longDesc: 'Hantera fakturor från frilansare korrekt. Nyckelfunktioner: F-skatt-kontroll, auto-kontosättning konto 4010, kostnad per projekt' },
      { slug: 'kulturmoms', name: 'Kulturmoms', cat: 'bokforing', desc: 'Moms 6% på publicering/film/kultur', longDesc: 'Hantera moms 6% vid publicering, film, kultur. Nyckelfunktioner: Korrekt momssats per tjänsttyp, blandad verksamhet' },
      { slug: 'ip-tillgangar', name: 'IP-tillgångar', cat: 'bokforing', desc: 'Immateriella rättigheter', longDesc: 'Aktivera och avskriva immateriella rättigheter. Nyckelfunktioner: Aktivering, avskrivningsplan, konto 1010/1020' },
      { slug: 'projektlonsamhet-media', name: 'Projektlönsamhet', cat: 'rapport', desc: 'Intäkt minus kostnad per projekt', longDesc: 'Intäkt minus kostnad per projekt. Nyckelfunktioner: Budget vs utfall, timkostnad vs debiterat' },
      { slug: 'freelancerandel', name: 'Freelancerandel', cat: 'rapport', desc: 'Freelancerkostnad av produktion', longDesc: 'Andel av produktionskostnad som går till freelancers. Nyckelfunktioner: Trend, lönsamhetspåverkan, per projekttyp' },
      { slug: 'kundlonsamhet', name: 'Kundlönsamhet', cat: 'rapport', desc: 'Intäkt och marginal per kund', longDesc: 'Intäkt och marginal per kund. Nyckelfunktioner: Tidsförbrukning vs fakturerat, återkommande kunder' },
      { slug: 'freelancer-fakturaimport', name: 'Freelancer-fakturaimport', cat: 'import', desc: 'Importera frilansarfakturor', longDesc: 'Importera fakturor från frilansare. Nyckelfunktioner: Parsning, F-skatt-verifiering, projektkoppling' },
      { slug: 'kampanjrapport-import', name: 'Kampanjrapport-import', cat: 'import', desc: 'Importera kampanjresultat', longDesc: 'Importera kampanjresultat. Nyckelfunktioner: Intäkter per kampanj, provisionskostnader' },
      { slug: 'projekthantering-media', name: 'Projekthantering', cat: 'operativ', desc: 'Styra kundprojekt', longDesc: 'Styra kundprojekt. Nyckelfunktioner: Projekttavla, tidslinje, kundgodkännande' },
      { slug: 'innehallsplanering', name: 'Innehållsplanering', cat: 'operativ', desc: 'Redaktionskalender', longDesc: 'Redaktionskalender. Nyckelfunktioner: Kanalvy, statusflöde, deadlines' },
      { slug: 'mediebank', name: 'Mediebank', cat: 'operativ', desc: 'Lagring av bilder, video, grafik', longDesc: 'Central lagring av media. Nyckelfunktioner: Taggning, sök, rättighetsspårning' },
      { slug: 'tidrapport-debitering-media', name: 'Tidrapport & Debitering', cat: 'operativ', desc: 'Logga tid per kund', longDesc: 'Logga tid per kund. Nyckelfunktioner: Timer, budget vs utfall, fakturaunderlag' },
    ],
  },
  {
    slug: 'fitness', name: 'Fitness & Sport', icon: Dumbbell,
    description: 'Medlemskap, klasser & pass',
    modules: [
      { slug: 'fitnesskontoplan', name: 'Fitnesskontoplan', cat: 'bokforing', desc: 'BAS-konton: medlemskap, PT, klippkort, shop', longDesc: 'BAS-konton per intäktstyp: medlemskap, PT, klippkort, shop. Nyckelfunktioner: Konton 3010 (medlemsavgift), 3020 (PT), 2420 (klippkortsskuld), 3030 (shop)' },
      { slug: 'momssplit-idrott-pt', name: 'Momssplit idrott/PT', cat: 'bokforing', desc: 'Moms 6% idrott, 25% PT/spa/shop', longDesc: 'Moms 6% på idrottslig verksamhet, 25% på PT, spa, shop. Nyckelfunktioner: Automatisk momssats per tjänsttyp, blandad verksamhet' },
      { slug: 'autogiro-periodisering', name: 'Autogiro-periodisering', cat: 'bokforing', desc: 'Autogiro som intäkt rätt period', longDesc: 'Bokför autogiro-dragningar som intäkt rätt period. Nyckelfunktioner: Förskottsbetalning, periodisering konto 2970, misslyckade dragningar' },
      { slug: 'klippkort-som-skuld', name: 'Klippkort som skuld', cat: 'bokforing', desc: 'Klippkort som förutbetald intäkt', longDesc: 'Sålda klippkort/startpaket bokförs som förutbetald intäkt. Nyckelfunktioner: Konto 2420, intäktsföring per nyttjat tillfälle, förfallohantering' },
      { slug: 'friskvardsbidrag', name: 'Friskvårdsbidrag', cat: 'bokforing', desc: 'Friskvårdsbidrag (max 5 000 SEK)', longDesc: 'Hantera friskvårdsbidrag från arbetsgivare. Nyckelfunktioner: Skatteverkets gräns (5 000 SEK), kvittogenerering, dokumentation' },
      { slug: 'churn-rate', name: 'Churn rate', cat: 'rapport', desc: 'Medlemsavgång per månad', longDesc: 'Medlemsavgång per månad. Nyckelfunktioner: Trend, orsaksanalys, retention per avtalstyp' },
      { slug: 'intakt-per-medlem', name: 'Intäkt per medlem', cat: 'rapport', desc: 'Genomsnittlig intäkt per medlem', longDesc: 'Genomsnittlig intäkt per aktiv medlem. Nyckelfunktioner: Inklusive PT, shop, extra tjänster' },
      { slug: 'belaggningsgrad-klasser', name: 'Beläggningsgrad klasser', cat: 'rapport', desc: 'Fyllnadsgrad per träningspass', longDesc: 'Fyllnadsgrad per gruppträningspass. Nyckelfunktioner: Per klass/tid, optimering av schema' },
      { slug: 'autogiro-rapport-import', name: 'Autogiro-rapport-import', cat: 'import', desc: 'Importera autogiro (Bankgirot)', longDesc: 'Importera autogiro-dragningsrapport (Bankgirot). Nyckelfunktioner: Lyckade/misslyckade, auto-kontosättning, period-matchning' },
      { slug: 'kassarapport-import-fitness', name: 'Kassarapport-import', cat: 'import', desc: 'Importera dagskassa', longDesc: 'Importera dagskassa. Nyckelfunktioner: Drop-in, PT-paket, shop; auto-kontosättning' },
      { slug: 'medlemshantering', name: 'Medlemshantering', cat: 'operativ', desc: 'Registrera och hantera medlemskap', longDesc: 'Registrera och hantera medlemskap. Nyckelfunktioner: Avtalstyper, förnyelse, uppsägning' },
      { slug: 'klassbokning', name: 'Klassbokning', cat: 'operativ', desc: 'Boka platser i träningsklasser', longDesc: 'Boka platser i träningspass. Nyckelfunktioner: Schema, platsbegränsning, väntelista' },
      { slug: 'pt-bokning', name: 'PT-bokning', cat: 'operativ', desc: 'Boka personlig tränare', longDesc: 'Boka personlig tränare. Nyckelfunktioner: Paket, kundhistorik, kalender' },
      { slug: 'tilltradeskontroll', name: 'Tillträdeskontroll', cat: 'operativ', desc: 'Inpassering till anläggning', longDesc: 'Inpassering till anläggning. Nyckelfunktioner: Nyckelbricka/QR, besökslogg' },
    ],
  },
  {
    slug: 'fordon', name: 'Fordon & Verkstad', icon: Wrench,
    description: 'Arbetsorder, delar & fordon',
    modules: [
      { slug: 'verkstadskontoplan', name: 'Verkstadskontoplan', cat: 'bokforing', desc: 'BAS-konton: arbete, reservdelar, besiktning', longDesc: 'BAS-konton per intäktstyp: arbete, reservdelar, besiktning. Nyckelfunktioner: Konton 3010 (arbetsintäkt), 3020 (reservdelar), 4010 (inköp reservdelar)' },
      { slug: 'arbetsorder-till-faktura', name: 'Arbetsorder → Faktura', cat: 'bokforing', desc: 'Faktura direkt från arbetsorder', longDesc: 'Generera faktura direkt från arbetsorder. Nyckelfunktioner: Timpris + delar, automatisk summering, konto-koppling' },
      { slug: 'reservdelslager', name: 'Reservdelslager', cat: 'bokforing', desc: 'Lagervärdering reservdelar (FIFO)', longDesc: 'Lagervärdering av reservdelar. Nyckelfunktioner: FIFO, konto 1460, månadsbokslut, inkuransavdrag' },
      { slug: 'vmb-begagnade-delar', name: 'VMB (begagnade delar)', cat: 'bokforing', desc: 'Vinstmarginalbeskattning', longDesc: 'Vinstmarginalbeskattning vid försäljning av begagnade reservdelar. Nyckelfunktioner: Beräkning av vinstmarginal, moms enbart på marginalen, konto 2640' },
      { slug: 'garantiavsattning', name: 'Garantiavsättning', cat: 'bokforing', desc: 'Avsätt för garantikostnader', longDesc: 'Avsätt för framtida garantikostnader. Nyckelfunktioner: Avsättning konto 2290, upplösning vid faktisk kostnad' },
      { slug: 'genomsnittligt-ordervarde', name: 'Genomsnittligt ordervärde', cat: 'rapport', desc: 'Snittfaktura per arbetsorder', longDesc: 'Snittfaktura per arbetsorder. Nyckelfunktioner: Arbete vs delar, trend, kundtypsanalys' },
      { slug: 'reservdelsmarginal', name: 'Reservdelsmarginal', cat: 'rapport', desc: 'Inpris vs utpris på delar', longDesc: 'Inpris vs utpris på delar. Nyckelfunktioner: Per kategori, trend' },
      { slug: 'verkstadsbelaggning', name: 'Verkstadsbeläggning', cat: 'rapport', desc: 'Utnyttjandegrad lyftar/mekaniker', longDesc: 'Utnyttjandegrad av lyftar och mekaniker. Nyckelfunktioner: Per resurs, optimering' },
      { slug: 'reservdelsleverantor-import', name: 'Reservdelsleverantör-import', cat: 'import', desc: 'Importera från Mekonomen, Autoexperten', longDesc: 'Importera priser och leveranser. Nyckelfunktioner: Mekonomen, Autoexperten-format, auto-kontosättning' },
      { slug: 'arbetsorder', name: 'Arbetsorder', cat: 'operativ', desc: 'Skapa och hantera verkstadsarbeten', longDesc: 'Skapa och hantera arbeten. Nyckelfunktioner: Registrering, mekaniker-tilldelning, statusflöde' },
      { slug: 'fordonsregister', name: 'Fordonsregister', cat: 'operativ', desc: 'Register med fordonshistorik', longDesc: 'Register med fordonshistorik. Nyckelfunktioner: Regnummer, servicehistorik, besiktningsdatum' },
      { slug: 'verkstadsplanering', name: 'Verkstadsplanering', cat: 'operativ', desc: 'Beläggning av lyftar och personal', longDesc: 'Beläggning av lyftar och personal. Nyckelfunktioner: Kalendervy, bokningstider, akut-slot' },
      { slug: 'besiktningspaminnelse', name: 'Besiktningspåminnelse', cat: 'operativ', desc: 'Påminnelser inför besiktning', longDesc: 'Automatiska påminnelser. Nyckelfunktioner: SMS/e-post, historik' },
    ],
  },
  {
    slug: 'bemanning', name: 'Bemanning & HR', icon: UserPlus,
    description: 'Kandidater, uppdrag & timmar',
    modules: [
      { slug: 'bemanningskontoplan', name: 'Bemanningskontoplan', cat: 'bokforing', desc: 'BAS-konton: uthyrning, rekrytering, UE, löner', longDesc: 'BAS-konton per intäkts- och kostnadstyp: uthyrning, rekrytering, underkonsulter. Nyckelfunktioner: Konton 3010 (uthyrningsintäkt), 3020 (rekryteringsarvode), 4010 (UE-kostnad), 7010 (löner)' },
      { slug: 'tidrapport-dubbelbokforing', name: 'Tidrapport → Dubbelbokföring', cat: 'bokforing', desc: 'Genererar kundfaktura och löneunderlag', longDesc: 'Tidrapport genererar både kundfaktura och löneunderlag. Nyckelfunktioner: Timrapport, kunddebitering, lönekostnad, marginalberäkning per uppdrag' },
      { slug: 'arbetsgivaravgifter-periodisering', name: 'Arbetsgivaravgifter-periodisering', cat: 'bokforing', desc: 'Periodisera arbetsgivaravgifter (31.42%)', longDesc: 'Periodisera arbetsgivaravgifter korrekt per månad. Nyckelfunktioner: Beräkning per anställd, konto 7510, semesterlöneskuld, period-vy' },
      { slug: 'ue-verifiering-bemanning', name: 'UE-verifiering', cat: 'bokforing', desc: 'F-skatt och försäkring för underkonsulter', longDesc: 'Kontrollera F-skatt och försäkring för underkonsulter. Nyckelfunktioner: Skatteverkets API-kontroll, dokumentation, fakturamottagning' },
      { slug: 'traktamente-vid-uthyrning', name: 'Traktamente vid uthyrning', cat: 'bokforing', desc: 'Traktamente per Skatteverkets schabloner', longDesc: 'Beräkna traktamente för uthyrd personal. Nyckelfunktioner: Skatteverkets schabloner, skattefri del, förmånsbeskattning vid övernattning' },
      { slug: 'marginal-per-konsult', name: 'Marginal per konsult', cat: 'rapport', desc: 'Debiterat minus lönekostnad', longDesc: 'Debiterat minus lönekostnad per uthyrd person. Nyckelfunktioner: Per uppdrag, trend, jämförelse' },
      { slug: 'belaggningsgrad-bemanning', name: 'Beläggningsgrad', cat: 'rapport', desc: 'Andel uthyrd tid', longDesc: 'Andel uthyrd tid av total tid. Nyckelfunktioner: Per konsult, team, totalt' },
      { slug: 'fakturerat-per-konsult', name: 'Fakturerat per konsult', cat: 'rapport', desc: 'Total fakturering per person', longDesc: 'Total fakturering per person och period. Nyckelfunktioner: Ranking, budget vs utfall' },
      { slug: 'tidrapport-import-bemanning', name: 'Tidrapport-import', cat: 'import', desc: 'Importera timmar från kundsystem', longDesc: 'Importera timmar från kundsystem. Nyckelfunktioner: CSV, kundgodkännande-status, auto-koppling till uppdrag' },
      { slug: 'lonesystem-import', name: 'Lönesystem-import', cat: 'import', desc: 'Importera från Hogia/Visma Lön', longDesc: 'Importera löneunderlag. Nyckelfunktioner: Export från Hogia, Visma Lön; auto-bokföring av lön + sociala avgifter' },
      { slug: 'kandidatregister', name: 'Kandidatregister', cat: 'operativ', desc: 'Rekryteringsdatabas', longDesc: 'Rekryteringsdatabas. Nyckelfunktioner: CV, kompetens, status, GDPR-rensning' },
      { slug: 'uppdragshantering-bemanning', name: 'Uppdragshantering', cat: 'operativ', desc: 'Matcha kandidater med uppdrag', longDesc: 'Matcha kandidater med uppdrag. Nyckelfunktioner: Kravprofil, matchning, förlängning' },
      { slug: 'avtalshantering-bemanning', name: 'Avtalshantering', cat: 'operativ', desc: 'Kundavtal och konsultavtal', longDesc: 'Kundavtal och konsultavtal. Nyckelfunktioner: Templates, förnyelsepåminnelser' },
      { slug: 'kompetensregister', name: 'Kompetensregister', cat: 'operativ', desc: 'Certifieringar och utbildningar', longDesc: 'Certifieringar och utbildningar. Nyckelfunktioner: Per person, giltighetstid' },
      { slug: 'compliance-bemanning', name: 'Compliance', cat: 'operativ', desc: 'ID06, arbetstillstånd, försäkringar', longDesc: 'Lagar och branschkrav. Nyckelfunktioner: ID06-kontroll, arbetstillstånd' },
    ],
  },
  {
    slug: 'tillverkning', name: 'Tillverkning & Industri', icon: Factory,
    description: 'Produktion, lager & kvalitet',
    modules: [
      { slug: 'tillverkningskontoplan', name: 'Tillverkningskontoplan', cat: 'bokforing', desc: 'BAS-konton per lagertyp och kostnadsställe', longDesc: 'BAS-konton per lagertyp och kostnadsställe. Nyckelfunktioner: Konton 1410 (råvarulager), 1420 (PIA), 1450 (färdigvarulager), 4010 (materialinköp)' },
      { slug: 'trestegslagervarderin', name: 'Trestegslagervärdering', cat: 'bokforing', desc: 'Värdera råvaror, PIA och färdigvaror', longDesc: 'Värdera råvaror, halvfabrikat (PIA) och färdigvaror separat. Nyckelfunktioner: FIFO per lagernivå, omvärdering vid produktion, konto 1410/1420/1450' },
      { slug: 'bom-kalkyl-lagervarde', name: 'BOM-kalkyl → Lagervärde', cat: 'bokforing', desc: 'Strukturlista styr självkostnad', longDesc: 'Strukturlista (BOM) styr självkostnad per tillverkad enhet. Nyckelfunktioner: Materialkomponenter, arbetskostnad, OH-pålägg, lagervärde per BOM' },
      { slug: 'produktionsavvikelse', name: 'Produktionsavvikelse', cat: 'bokforing', desc: 'Avvikelse standard vs faktisk kostnad', longDesc: 'Bokför avvikelse mellan kalkylerad och faktisk kostnad. Nyckelfunktioner: Standard- vs verklig kostnad, avvikelsekonto 4900' },
      { slug: 'maskinavskrivning-industri', name: 'Maskinavskrivning', cat: 'bokforing', desc: 'Avskrivning produktionsutrustning', longDesc: 'Avskrivningsplan för produktionsutrustning. Nyckelfunktioner: Räkenskapsenlig avskrivning, konto 1210/7831, restvärdeavskrivning' },
      { slug: 'energiskatteavdrag', name: 'Energiskatteavdrag', cat: 'bokforing', desc: 'Avdrag för energiskatt vid industri', longDesc: 'Avdrag för energiskatt vid industriell tillverkning. Nyckelfunktioner: Nedsättning av energiskatt, ansökan till Skatteverket, periodisering' },
      { slug: 'materialeffektivitet', name: 'Materialeffektivitet', cat: 'rapport', desc: 'Faktisk vs BOM-förbrukning', longDesc: 'Faktisk materialförbrukning vs BOM-kalkyl. Nyckelfunktioner: Spill %, kostnad för avvikelse, trend' },
      { slug: 'kostnad-per-producerad-enhet', name: 'Kostnad per producerad enhet', cat: 'rapport', desc: 'Total enhetskostnad', longDesc: 'Total kostnad (material + arbete + OH) per enhet. Nyckelfunktioner: Per produkt, period-jämförelse' },
      { slug: 'oee', name: 'OEE', cat: 'rapport', desc: 'Overall Equipment Effectiveness', longDesc: 'Maskinutnyttjandegrad. Nyckelfunktioner: Tillgänglighet × prestanda × kvalitet' },
      { slug: 'produktionsrapport-import', name: 'Produktionsrapport-import', cat: 'import', desc: 'Importera utfallsdata per order', longDesc: 'Importera utfallsdata per tillverkningsorder. Nyckelfunktioner: Godkänt/kasserat, materialförbrukning, auto-kontosättning' },
      { slug: 'lagerexport-import', name: 'Lagerexport-import', cat: 'import', desc: 'Importera lagerförändringar', longDesc: 'Importera lagerförändringar. Nyckelfunktioner: Per lagernivå, inventeringsresultat' },
      { slug: 'produktionsplanering', name: 'Produktionsplanering', cat: 'operativ', desc: 'Schemalägga tillverkningsorder', longDesc: 'Schemalägga tillverkningsorder. Nyckelfunktioner: Ordervy, maskinbeläggning, kapacitet' },
      { slug: 'strukturlista-bom', name: 'Strukturlista (BOM)', cat: 'operativ', desc: 'Materialstruktur per produkt', longDesc: 'Definiera materialstruktur. Nyckelfunktioner: Komponenter, nivåer, alternativa delar' },
      { slug: 'kvalitetskontroll', name: 'Kvalitetskontroll', cat: 'operativ', desc: 'Säkerställ produktkvalitet', longDesc: 'Säkerställ produktkvalitet. Nyckelfunktioner: Kontrollplaner, mätprotokoll, avvikelser' },
      { slug: 'maskinunderhall', name: 'Maskinunderhåll', cat: 'operativ', desc: 'Förebyggande underhåll', longDesc: 'Förebyggande och avhjälpande underhåll. Nyckelfunktioner: Schema, felanmälan, reservdelsförbrukning' },
      { slug: 'sparbarhet-batch', name: 'Spårbarhet & Batch', cat: 'operativ', desc: 'Spåra råvaror till färdig produkt', longDesc: 'Spåra råvaror till färdig produkt. Nyckelfunktioner: Batchnummer, komponentspårning, återkallning' },
    ],
  },
  {
    slug: 'konsult', name: 'Konsult & Rådgivning', icon: Briefcase,
    description: 'Uppdrag, tid & debitering',
    modules: [
      { slug: 'konsultkontoplan', name: 'Konsultkontoplan', cat: 'bokforing', desc: 'BAS-konton: arvode, resor, utlägg', longDesc: 'BAS-konton för konsultintäkt, utlägg, resor. Nyckelfunktioner: Konton 3010 (konsultarvode), 5800 (resekostnad), 6990 (vidarefakturerade utlägg)' },
      { slug: 'traktamente', name: 'Traktamente', cat: 'bokforing', desc: 'Traktamente per Skatteverkets schabloner', longDesc: 'Beräkna traktamente vid tjänsteresor enligt Skatteverkets schabloner. Nyckelfunktioner: Hel/halvdag, reducering vid fri måltid, skattefri del, förmånsvärde' },
      { slug: 'hemmakontor-avdrag', name: 'Hemmakontor-avdrag', cat: 'bokforing', desc: 'Schablonavdrag (2000/4000 SEK)', longDesc: 'Schablonavdrag för hemmakontor. Nyckelfunktioner: Fast belopp (2 000/4 000 SEK), alternativt verklig kostnad med yta-beräkning' },
      { slug: 'wip-bevakning-konsult', name: 'WIP-bevakning', cat: 'bokforing', desc: 'Pågående ej fakturerat arbete', longDesc: 'Pågående ej fakturerat arbete. Nyckelfunktioner: Konto 1470, per uppdrag, åldringsanalys' },
      { slug: 'debiteringsgrad-konsult', name: 'Debiteringsgrad', cat: 'rapport', desc: 'Debiterbara timmar av total', longDesc: 'Debiterbara timmar / total arbetstid. Nyckelfunktioner: Mål vs utfall, trend' },
      { slug: 'intakt-per-konsult', name: 'Intäkt per konsult', cat: 'rapport', desc: 'Total fakturering per person', longDesc: 'Total fakturering per person. Nyckelfunktioner: Ranking, budget vs utfall' },
      { slug: 'tidrapport-import-konsult', name: 'Tidrapport-import', cat: 'import', desc: 'Importera från Harvest, Toggl', longDesc: 'Importera tid från Harvest, Toggl, Clockify. Nyckelfunktioner: CSV, koppling till uppdrag, fakturaunderlag' },
      { slug: 'uppdragshantering-konsult', name: 'Uppdragshantering', cat: 'operativ', desc: 'Administrera kunduppdrag', longDesc: 'Administrera kunduppdrag. Nyckelfunktioner: Milstolpar, statusvy, lönsamhetsanalys' },
      { slug: 'tidrapportering-konsult', name: 'Tidrapportering', cat: 'operativ', desc: 'Tidregistrering per uppdrag', longDesc: 'Detaljerad tidregistrering. Nyckelfunktioner: Timer, kategorier, veckoöversikt' },
      { slug: 'offert-avtal', name: 'Offert & Avtal', cat: 'operativ', desc: 'Skapa offerter och avtal', longDesc: 'Skapa offerter. Nyckelfunktioner: Mallar, godkännande, avtalsstatus' },
    ],
  },
  {
    slug: 'event', name: 'Event & Underhållning', icon: PartyPopper,
    description: 'Evenemang, biljetter & artister',
    modules: [
      { slug: 'eventkontoplan', name: 'Eventkontoplan', cat: 'bokforing', desc: 'BAS-konton: biljetter, sponsring, F&B, merch', longDesc: 'BAS-konton per intäktstyp: biljetter, sponsring, F&B, merch. Nyckelfunktioner: Konton 3010 (biljettintäkt), 3020 (sponsorintäkt), 3030 (F&B), 3040 (merch)' },
      { slug: 'biljettintakt-som-forskott', name: 'Biljettintäkt som förskott', cat: 'bokforing', desc: 'Förskottssålda biljetter som skuld', longDesc: 'Bokför förskottssålda biljetter som skuld tills eventet äger rum. Nyckelfunktioner: Konto 2420, intäktsföring vid genomfört event, avbokningshantering' },
      { slug: 'kulturmoms-event', name: 'Kulturmoms event', cat: 'bokforing', desc: 'Moms 6% kultur, 25% F&B/merch', longDesc: 'Hantera reducerad moms på kulturella föreställningar. Nyckelfunktioner: Moms 6% på biljetter, 25% på mat/dryck/merch, blandad verksamhet' },
      { slug: 'artistskatt-sink', name: 'Artistskatt (SINK)', cat: 'bokforing', desc: 'SINK-skatt (15%) utländska artister', longDesc: 'Hantera källskatt för utländska artister. Nyckelfunktioner: Beräkning av SINK (15%), inbetalning till Skatteverket, underlag per artist' },
      { slug: 'sponsorintaktsbokforing', name: 'Sponsorintäktsbokföring', cat: 'bokforing', desc: 'Sponsoravtal med periodisering', longDesc: 'Bokför sponsoravtal med motprestationsperiodisering. Nyckelfunktioner: Periodisering per event, konto 3910, avtalsvärde vs motprestation' },
      { slug: 'intakt-per-besokare', name: 'Intäkt per besökare', cat: 'rapport', desc: 'Total intäkt per besökare', longDesc: 'Total intäkt delat på antal besökare. Nyckelfunktioner: Biljett + F&B + merch, jämförelse mellan event' },
      { slug: 'budget-vs-utfall', name: 'Budget vs utfall', cat: 'rapport', desc: 'Eventbudget vs verkligt resultat', longDesc: 'Eventbudget jämfört med verkligt resultat. Nyckelfunktioner: Per kostnadspost, totalt, vinstmarginal' },
      { slug: 'sponsorandel', name: 'Sponsorandel', cat: 'rapport', desc: 'Sponsorintäkt som andel av total', longDesc: 'Sponsorintäkt som andel av total intäkt. Nyckelfunktioner: Per event, trend, beroendeanalys' },
      { slug: 'biljettsystem-import', name: 'Biljettsystem-import', cat: 'import', desc: 'Importera från Ticketmaster, Eventbrite', longDesc: 'Importera försäljningsdata från biljettsystem. Nyckelfunktioner: Ticketmaster, Eventbrite, NORTIC; auto-kontosättning inkl avgifter' },
      { slug: 'pos-rapport-import-event', name: 'POS-rapport-import', cat: 'import', desc: 'Importera F&B- och merch-försäljning', longDesc: 'Importera F&B- och merch-försäljning. Nyckelfunktioner: Kassarapport från eventbar/shop, momssplit' },
      { slug: 'evenemangsplanering', name: 'Evenemangsplanering', cat: 'operativ', desc: 'Planera och koordinera event', longDesc: 'Planera och koordinera event. Nyckelfunktioner: Checklista, tidslinje, budget' },
      { slug: 'biljettforsaljning', name: 'Biljettförsäljning', cat: 'operativ', desc: 'Sälj och hantera biljetter', longDesc: 'Sälj och hantera biljetter. Nyckelfunktioner: Biljettyper, priskategorier, QR-validering' },
      { slug: 'artist-talangbokning', name: 'Artist- & Talangbokning', cat: 'operativ', desc: 'Boka artister och föreläsare', longDesc: 'Boka artister och föreläsare. Nyckelfunktioner: Kontrakt, riderhantering, schema' },
      { slug: 'sponsorhantering', name: 'Sponsorhantering', cat: 'operativ', desc: 'Hantera sponsoravtal', longDesc: 'Hantera sponsoravtal. Nyckelfunktioner: Avtalsnivåer, motprestationer, uppföljning' },
      { slug: 'volontarhantering', name: 'Volontärhantering', cat: 'operativ', desc: 'Koordinera frivilliga', longDesc: 'Koordinera frivilliga. Nyckelfunktioner: Registrering, skifttilldelning, kommunikation' },
    ],
  },
  {
    slug: 'fastighet', name: 'Fastighetsförvaltning', icon: Building,
    description: 'Objekt, hyresgäster & underhåll',
    modules: [
      { slug: 'fastighetskontoplan', name: 'Fastighetskontoplan', cat: 'bokforing', desc: 'BAS-konton per fastighet och kostnadstyp', longDesc: 'BAS-konton per fastighet och kostnadstyp. Nyckelfunktioner: Konton 1110 (byggnader), 3010 (hyresintäkt), 5010 (fastighetsskötsel), 7720 (fastighetsskatt)' },
      { slug: 'hyresintakt-periodisering', name: 'Hyresintäkt-periodisering', cat: 'bokforing', desc: 'Periodisera hyresintäkter per månad', longDesc: 'Periodisera hyresintäkter korrekt per månad. Nyckelfunktioner: Förskottshyra (konto 2970), hyresrabatt, tomgångskostnad' },
      { slug: 'fastighetsskatt', name: 'Fastighetsskatt', cat: 'bokforing', desc: 'Beräkna fastighetsskatt/avgift', longDesc: 'Beräkna och bokföra fastighetsskatt/avgift. Nyckelfunktioner: Taxeringsvärde, skattesats per fastighetstyp, konto 7720, periodisering' },
      { slug: 'fastighetsavskrivning', name: 'Fastighetsavskrivning', cat: 'bokforing', desc: 'Avskrivning per byggnad (K2/K3)', longDesc: 'Avskrivningsplan per byggnad (lång löptid). Nyckelfunktioner: Komponentavskrivning (K3) eller linjär (K2), konto 1119/7820' },
      { slug: 'underhallsfond', name: 'Underhållsfond', cat: 'bokforing', desc: 'Avsätt medel för planerat underhåll', longDesc: 'Avsätt medel för planerat underhåll. Nyckelfunktioner: Avsättning per år, upplösning vid genomfört underhåll, 10-årsplan kopplad' },
      { slug: 'rot-vid-renovering', name: 'ROT vid renovering', cat: 'bokforing', desc: 'ROT-avdrag vid renovering', longDesc: 'Hantera ROT-avdrag för hyresgäster vid renovering. Nyckelfunktioner: Beräkning, personnummer, Skatteverket-rapportering' },
      { slug: 'indexupprakning', name: 'Indexuppräkning', cat: 'bokforing', desc: 'Automatisk hyreshöjning vid index', longDesc: 'Automatisk beräkning av hyreshöjning vid index. Nyckelfunktioner: KPI-koppling, beräkning per kontrakt, underlag för avisering' },
      { slug: 'driftnetto-per-fastighet', name: 'Driftnetto per fastighet', cat: 'rapport', desc: 'NOI per fastighet', longDesc: 'Hyresintäkt minus driftskostnad. Nyckelfunktioner: Per fastighet/objekt, jämförelse, trend' },
      { slug: 'vakansgrad', name: 'Vakansgrad', cat: 'rapport', desc: 'Andel outhyrda ytor', longDesc: 'Andel outhyrda ytor. Nyckelfunktioner: Per fastighet, trendanalys, intäktsbortfall' },
      { slug: 'underhallskostnad-per-m2', name: 'Underhållskostnad per m²', cat: 'rapport', desc: 'Underhåll per kvadratmeter', longDesc: 'Total underhållskostnad per kvadratmeter. Nyckelfunktioner: Plan vs utfall, per fastighet, kategori' },
      { slug: 'hyresreskontra-import', name: 'Hyresreskontra-import', cat: 'import', desc: 'Importera hyresreskontra', longDesc: 'Importera hyresreskontra. Nyckelfunktioner: Avier, betalningar, restbelopp; auto-kontosättning' },
      { slug: 'energirapport-import', name: 'Energirapport-import', cat: 'import', desc: 'Importera energiförbrukning', longDesc: 'Importera energiförbrukning. Nyckelfunktioner: El/vatten/fjärrvärme, per fastighet, kostnadsfördelning' },
      { slug: 'objektregister', name: 'Objektregister', cat: 'operativ', desc: 'Fastighets- och lokalöversikt', longDesc: 'Fastighets- och lokalöversikt. Nyckelfunktioner: Adresser, ytor, byggnadsår, dokument' },
      { slug: 'hyresgasthantering', name: 'Hyresgästhantering', cat: 'operativ', desc: 'Administrera hyresavtal', longDesc: 'Administrera hyresavtal. Nyckelfunktioner: Avtalstider, kontakt, uppsägningsflöde' },
      { slug: 'hyresavier', name: 'Hyresavier', cat: 'operativ', desc: 'Generera och skicka avier', longDesc: 'Generera och skicka avier. Nyckelfunktioner: Automatisk avisering, tillägg, autogiro' },
      { slug: 'felanmalan', name: 'Felanmälan', cat: 'operativ', desc: 'Hantera felanmälningar', longDesc: 'Hantera felanmälningar. Nyckelfunktioner: Webformulär, prioritet, hantverkarstyrning' },
      { slug: 'underhallsplanering', name: 'Underhållsplanering', cat: 'operativ', desc: 'Långsiktig underhållsplanering', longDesc: 'Långsiktig och akut. Nyckelfunktioner: 10-årsplan, kostnadsprognos, status' },
      { slug: 'besiktning-rondering', name: 'Besiktning & Rondering', cat: 'operativ', desc: 'Dokumentera besiktningar', longDesc: 'Dokumentera besiktningar. Nyckelfunktioner: Protokoll, foto, avvikelserapport' },
      { slug: 'energiovervakning', name: 'Energiövervakning', cat: 'operativ', desc: 'Följ energiförbrukning', longDesc: 'Följ energiförbrukning. Nyckelfunktioner: El/vatten/värme, jämförelse, energideklaration' },
    ],
  },
]

export function getSectorBySlug(slug: string): Sector | undefined {
  return sectors.find(s => s.slug === slug)
}

export function getModuleBySlug(sectorSlug: string, moduleSlug: string): { sector: Sector; module: ModuleItem } | undefined {
  const sector = sectors.find(s => s.slug === sectorSlug)
  if (!sector) return undefined
  const module = sector.modules.find(m => m.slug === moduleSlug)
  if (!module) return undefined
  return { sector, module }
}
